"""Generate the data-dependent Lean modules of the Kobon certificate.

    python3 gen.py SOLUTION.json PROJECT_DIR [REPORT.json]

Writes, under PROJECT_DIR/KobonCert/:
  Data.lean      the lines `sol`, the claimed triangles `R_i` (those with smallest line index i)
                 and `reportFaces` = their concatenation
  Chunk/F*.lean  kernel computations: (rowTriples n i).filter (faceB sol) = R_i
  Chunk/E*.lean  the same for the transcription of eval.py (evalFaceB)
  Simple.lean    general position (only if the arrangement is simple)
  Cert.lean      validity, gluing of the rows, the counts (literal n and count)
  Main.lean      final statements with literal numbers, `#print axioms`
  chunks.txt     module list for tools/build.sh;  values.json  n, count, simple

The triangle list is taken from REPORT.json (`details.triangle_line_indices` of the hill's
report) if given, otherwise it is recomputed here with a plain-integer port of the determinant
test.  Either way the list is only a claim: the Lean kernel recomputes every row.  Nothing in
the Lean statements depends on this script being right, except that `sol` must equal the JSON
data (and `reportFaces` the report): that is checked independently by tools/check_data.py.

Environment: ROWMAX (default 400) = maximal number of index triples per chunk module when
several short rows are grouped (a single row is never split; row 0 has C(n-1, 2) triples).
"""
import json
import os
import sys
from itertools import combinations

sol_path, proj = sys.argv[1], sys.argv[2]
rep_path = sys.argv[3] if len(sys.argv) > 3 else None
lines = [tuple(r) for r in json.load(open(sol_path))["lines"]]
n = len(lines)
assert all(len(r) == 3 and all(type(v) is int for v in r) for r in lines)


def w(p, q): return p[0] * q[1] - p[1] * q[0]
def px(p, q): return p[1] * q[2] - p[2] * q[1]
def py(p, q): return p[2] * q[0] - p[0] * q[2]
def det3(l, p, q): return l[0] * px(p, q) + l[1] * py(p, q) + l[2] * w(p, q)
def sv(l, p, q): return det3(l, p, q) * w(p, q)


def tri(p, q, r):
    if w(p, q) == 0 or w(p, r) == 0 or w(q, r) == 0 or det3(p, q, r) == 0:
        return False
    for l in lines:
        s = (sv(l, p, q), sv(l, p, r), sv(l, q, r))
        if not (all(v >= 0 for v in s) or all(v <= 0 for v in s)):
            return False
    return True


own = [[i, j, k] for i, j, k in combinations(range(n), 3) if tri(lines[i], lines[j], lines[k])]
if rep_path:
    rep = json.load(open(rep_path))
    faces = rep["details"]["triangle_line_indices"]
    src = (f"details.triangle_line_indices of {os.path.basename(rep_path)} "
           f"(hill report, metric triangles = {rep['metrics'][0]['value']})")
    assert rep["details"]["index_base"] == 0
    if faces != own:
        print("WARNING: report triangle list differs from gen.py's own recount; the Lean check will fail")
else:
    faces = own
    src = "recomputed by tools/gen.py (no report given)"
assert faces == sorted(faces) and all(i < j < k for i, j, k in faces), "triangle list not sorted"
cnt = len(faces)
simple = all(w(p, q) != 0 for p, q in combinations(lines, 2)) and \
    all(det3(p, q, r) != 0 for p, q, r in combinations(lines, 3))
print(f"n = {n}, triangles = {cnt}, simple = {simple}")


def lit(v):
    return str(v) if v >= 0 else f"({v})"


def tl(ts):
    if not ts:
        return "[]"
    rows = [", ".join(f"({i}, {j}, {k})" for i, j, k in ts[s:s + 8]) for s in range(0, len(ts), 8)]
    return "[\n" + ",\n".join("  " + r for r in rows) + "\n]"


K = f"{proj}/KobonCert"
os.makedirs(f"{K}/Chunk", exist_ok=True)
for f in os.listdir(f"{K}/Chunk"):
    os.remove(f"{K}/Chunk/{f}")

d = ["/- GENERATED by tools/gen.py from solution.json -- do not edit. -/",
     "import KobonCert.Defs", "", "namespace Kobon", "",
     f"/-- The {n} lines of solution.json, in file order (line i is `[a, b, c]`: a*x + b*y + c = 0). -/",
     "def sol : List Line := ["]
d.append(",\n".join(f"  ⟨{lit(a)}, {lit(b)}, {lit(c)}⟩" for a, b, c in lines))
d += ["]", "", f"/- Claimed triangles (0-based line indices i < j < k), by smallest index i.",
      f"Source: {src}. -/"]
for i in range(n):
    d.append(f"def R_{i} : List (Nat × Nat × Nat) := " + tl([t for t in faces if t[0] == i]))
d += ["", "/-- all claimed triangles, in lexicographic order -/",
      "def reportFaces : List (Nat × Nat × Nat) :=",
      "  " + " ++ (".join(f"R_{i}" for i in range(n)) + " ++ []" + ")" * (n - 1),
      "", "end Kobon", ""]
open(f"{K}/Data.lean", "w", encoding="utf-8").write("\n".join(d))

# group consecutive rows into chunk modules
ROWMAX = int(os.environ.get("ROWMAX", "400"))
groups, cur, tot = [], [], 0
for i in range(n):
    sz = (n - 1 - i) * (n - 2 - i) // 2 if i < n - 2 else 0
    if cur and tot + sz > ROWMAX:
        groups.append(cur)
        cur, tot = [], 0
    cur.append(i)
    tot += sz
groups.append(cur)
mods = []
for kind, fn, pre in (("F", "faceB", "face"), ("E", "evalFaceB", "eface")):
    for g, rows in enumerate(groups):
        body = "\n".join(
            f"theorem {pre}_{i} : (rowTriples {n} {i}).filter ({fn} sol) = R_{i} := by decide +kernel"
            for i in rows)
        open(f"{K}/Chunk/{kind}{g}.lean", "w", encoding="utf-8").write(
            f"/- GENERATED by tools/gen.py: rows {rows[0]}..{rows[-1]} -/\nimport KobonCert.Data\n"
            f"namespace Kobon\n{body}\nend Kobon\n")
        mods.append(f"KobonCert.Chunk.{kind}{g}")
open(f"{K}/chunks.txt", "w").write("\n".join(mods) + "\n")
imports = "\n".join("import " + x for x in mods)
rng = ", ".join(str(i) for i in range(n))
flem = ", ".join(f"face_{i}" for i in range(n))
elem = ", ".join(f"eface_{i}" for i in range(n))

c = f"""/- GENERATED by tools/gen.py (literal numbers n = {n}, count = {cnt}) -- do not edit.
Kernel-checked facts about the concrete arrangement `sol`.  Every computation is `decide +kernel`:
the Lean kernel evaluates the Bool/Nat/List expression (exact integer arithmetic).  The heavy
part is split by rows (smallest line index) over the modules Chunk.F* / Chunk.E*. -/
import KobonCert.Data
{imports}

namespace Kobon

/-- accepted by the hill: {n} proper, pairwise distinct lines, coefficients within 10^30 -/
theorem sol_valid : validB {n} sol = true := by decide +kernel

theorem sol_length : sol.length = {n} := by decide +kernel

/-- the list of triangles is strictly increasing (so it has no repeated entry) -/
theorem reportFaces_inc : incB reportFaces = true := by decide +kernel

theorem reportFaces_length : reportFaces.length = {cnt} := by decide +kernel

theorem range_n : List.range {n} = [{rng}] := by decide +kernel

/-- determinant ("geometric") checker: the triangular faces are exactly the reported ones -/
theorem sol_faces : faces sol = reportFaces := by
  rw [faces, sol_length, idxTriples, range_n]
  simp only [List.flatMap_cons, List.flatMap_nil, List.filter_append, List.filter_nil,
    {flem}]
  rfl

/-- transcription of eval.py (consecutive vertices on each side): the same list -/
theorem sol_evalFaces : evalFaces sol = reportFaces := by
  rw [evalFaces, sol_length, idxTriples, range_n]
  simp only [List.flatMap_cons, List.flatMap_nil, List.filter_append, List.filter_nil,
    {elem}]
  rfl

theorem kobonCount_sol : kobonCount sol = {cnt} := by
  unfold kobonCount; rw [sol_faces]; exact reportFaces_length

theorem evalCount_sol : evalCount sol = {cnt} := by
  unfold evalCount; rw [sol_evalFaces]; exact reportFaces_length

end Kobon
"""
open(f"{K}/Cert.lean", "w", encoding="utf-8").write(c)

s = f"""/- GENERATED by tools/gen.py -- do not edit. -/
import KobonCert.Data

namespace Kobon

/-- general position: no two lines parallel, no three lines concurrent -/
theorem sol_simple : simpleB sol = true := by decide +kernel

end Kobon
"""
if simple:
    open(f"{K}/Simple.lean", "w", encoding="utf-8").write(s)
elif os.path.exists(f"{K}/Simple.lean"):
    os.remove(f"{K}/Simple.lean")

m = f"""/- GENERATED by tools/gen.py (literal numbers n = {n}, count = {cnt}) -- do not edit.
Final statements. -/
import KobonCert.Cert
{"import KobonCert.Simple" if simple else "-- arrangement is not simple: no Simple.lean"}
import KobonCert.Faces

namespace Kobon

/-- T1 (combinatorial certificate): the arrangement `sol` of solution.json is a valid
submission for n = {n} and has exactly {cnt} triangular faces, for the determinant checker
and for the transcription of the hill evaluator; both produce the reported list. -/
theorem certificate :
    validB {n} sol = true ∧ kobonCount sol = {cnt} ∧ evalCount sol = {cnt} ∧
    faces sol = reportFaces ∧ evalFaces sol = reportFaces :=
  ⟨sol_valid, kobonCount_sol, evalCount_sol, sol_faces, sol_evalFaces⟩

/-- T2 (geometric statement for the concrete arrangement): the index triples i < j < k < {n}
whose lines bound a triangular face in the sense of `IsTriFace` (real plane) are exactly
the {cnt} reported ones. -/
theorem sol_triFaces :
    {{t : ℕ × ℕ × ℕ | t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < {n} ∧
        IsTriFace sol (nth sol t.1) (nth sol t.2.1) (nth sol t.2.2)}}.ncard = {cnt} := by
  have h := ncard_triFaces sol (proper_of_validB sol_valid) reportFaces sol_faces reportFaces_inc
  rw [reportFaces_length, sol_length] at h
  exact h

/-- T2 (existence): there is an arrangement of {n} pairwise distinct lines in the real plane
with exactly {cnt} triangular faces in the sense of `IsTriFace`.  Hence K({n}) ≥ {cnt}. -/
theorem kobon_lower_bound :
    ∃ L : List Line, L.length = {n} ∧ (∀ l ∈ L, l.a ≠ 0 ∨ l.b ≠ 0) ∧
      L.Pairwise (fun p q => ¬ ∀ P : ℝ × ℝ, OnLine p P ↔ OnLine q P) ∧
      {{t : ℕ × ℕ × ℕ | t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < {n} ∧
        IsTriFace L (nth L t.1) (nth L t.2.1) (nth L t.2.2)}}.ncard = {cnt} :=
  ⟨sol, sol_length, proper_of_validB sol_valid, distinct_of_validB sol_valid, sol_triFaces⟩

/-- T2 (non-overlapping triangles; the usual meaning of K({n}) ≥ {cnt}): {n} pairwise distinct
lines in the real plane and {cnt} triples of them, each bounding a nondegenerate triangle
(vertices = the three pairwise intersection points) whose open interior meets none of the
{n} lines; the {cnt} open triangles are pairwise disjoint. -/
theorem kobon_nonoverlapping :
    ∃ (L : List Line) (T : Finset (ℕ × ℕ × ℕ)) (tri : ℕ × ℕ × ℕ → (ℝ × ℝ) × (ℝ × ℝ) × (ℝ × ℝ)),
      L.length = {n} ∧ (∀ l ∈ L, l.a ≠ 0 ∨ l.b ≠ 0) ∧
      L.Pairwise (fun p q => ¬ ∀ P : ℝ × ℝ, OnLine p P ↔ OnLine q P) ∧
      T.card = {cnt} ∧
      (∀ t ∈ T, t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < {n} ∧
        TriWitness L (nth L t.1) (nth L t.2.1) (nth L t.2.2) (tri t).1 (tri t).2.1 (tri t).2.2) ∧
      (∀ t ∈ T, ∀ t' ∈ T, t ≠ t' →
        Disjoint (openTri (tri t).1 (tri t).2.1 (tri t).2.2)
          (openTri (tri t').1 (tri t').2.1 (tri t').2.2)) := by
  obtain ⟨T, tri, hc, h1, h2⟩ := exists_family sol (proper_of_validB sol_valid)
    (distinct_of_validB sol_valid) reportFaces sol_faces reportFaces_inc
  refine ⟨sol, T, tri, sol_length, proper_of_validB sol_valid, distinct_of_validB sol_valid,
    by rw [hc, reportFaces_length], fun t ht => ?_, h2⟩
  have h := h1 t ht
  rw [sol_length] at h
  exact h

end Kobon

#print axioms Kobon.kobon_nonoverlapping
#print axioms Kobon.triFaces_disjoint
#print axioms Kobon.certificate
{"#print axioms Kobon.sol_simple" if simple else ""}
#print axioms Kobon.triCheck_iff
#print axioms Kobon.sol_triFaces
#print axioms Kobon.kobon_lower_bound
"""
open(f"{K}/Main.lean", "w", encoding="utf-8").write(m)
open(f"{K}/values.json", "w").write(json.dumps({"n": n, "triangles": cnt, "simple": simple}) + "\n")
