/- GENERATED by tools/gen.py: rows 17..18 -/
import KobonCert.Data
namespace Kobon
theorem eface_17 : (rowTriples 39 17).filter (evalFaceB sol) = R_17 := by decide +kernel
theorem eface_18 : (rowTriples 39 18).filter (evalFaceB sol) = R_18 := by decide +kernel
end Kobon
