/- GENERATED by tools/gen.py: rows 19..20 -/
import KobonCert.Data
namespace Kobon
theorem eface_19 : (rowTriples 39 19).filter (evalFaceB sol) = R_19 := by decide +kernel
theorem eface_20 : (rowTriples 39 20).filter (evalFaceB sol) = R_20 := by decide +kernel
end Kobon
