/- GENERATED by tools/gen.py: rows 21..23 -/
import KobonCert.Data
namespace Kobon
theorem eface_21 : (rowTriples 39 21).filter (evalFaceB sol) = R_21 := by decide +kernel
theorem eface_22 : (rowTriples 39 22).filter (evalFaceB sol) = R_22 := by decide +kernel
theorem eface_23 : (rowTriples 39 23).filter (evalFaceB sol) = R_23 := by decide +kernel
end Kobon
