/- GENERATED by tools/gen.py: rows 24..30 -/
import KobonCert.Data
namespace Kobon
theorem eface_24 : (rowTriples 39 24).filter (evalFaceB sol) = R_24 := by decide +kernel
theorem eface_25 : (rowTriples 39 25).filter (evalFaceB sol) = R_25 := by decide +kernel
theorem eface_26 : (rowTriples 39 26).filter (evalFaceB sol) = R_26 := by decide +kernel
theorem eface_27 : (rowTriples 39 27).filter (evalFaceB sol) = R_27 := by decide +kernel
theorem eface_28 : (rowTriples 39 28).filter (evalFaceB sol) = R_28 := by decide +kernel
theorem eface_29 : (rowTriples 39 29).filter (evalFaceB sol) = R_29 := by decide +kernel
theorem eface_30 : (rowTriples 39 30).filter (evalFaceB sol) = R_30 := by decide +kernel
end Kobon
