/- GENERATED by tools/gen.py: rows 31..38 -/
import KobonCert.Data
namespace Kobon
theorem eface_31 : (rowTriples 39 31).filter (evalFaceB sol) = R_31 := by decide +kernel
theorem eface_32 : (rowTriples 39 32).filter (evalFaceB sol) = R_32 := by decide +kernel
theorem eface_33 : (rowTriples 39 33).filter (evalFaceB sol) = R_33 := by decide +kernel
theorem eface_34 : (rowTriples 39 34).filter (evalFaceB sol) = R_34 := by decide +kernel
theorem eface_35 : (rowTriples 39 35).filter (evalFaceB sol) = R_35 := by decide +kernel
theorem eface_36 : (rowTriples 39 36).filter (evalFaceB sol) = R_36 := by decide +kernel
theorem eface_37 : (rowTriples 39 37).filter (evalFaceB sol) = R_37 := by decide +kernel
theorem eface_38 : (rowTriples 39 38).filter (evalFaceB sol) = R_38 := by decide +kernel
end Kobon
