/- GENERATED by tools/gen.py: rows 17..18 -/
import KobonCert.Data
namespace Kobon
theorem face_17 : (rowTriples 39 17).filter (faceB sol) = R_17 := by decide +kernel
theorem face_18 : (rowTriples 39 18).filter (faceB sol) = R_18 := by decide +kernel
end Kobon
