/- GENERATED by tools/gen.py: rows 19..20 -/
import KobonCert.Data
namespace Kobon
theorem face_19 : (rowTriples 39 19).filter (faceB sol) = R_19 := by decide +kernel
theorem face_20 : (rowTriples 39 20).filter (faceB sol) = R_20 := by decide +kernel
end Kobon
