/- GENERATED by tools/gen.py: rows 21..23 -/
import KobonCert.Data
namespace Kobon
theorem face_21 : (rowTriples 39 21).filter (faceB sol) = R_21 := by decide +kernel
theorem face_22 : (rowTriples 39 22).filter (faceB sol) = R_22 := by decide +kernel
theorem face_23 : (rowTriples 39 23).filter (faceB sol) = R_23 := by decide +kernel
end Kobon
