/- GENERATED by tools/gen.py: rows 24..30 -/
import KobonCert.Data
namespace Kobon
theorem face_24 : (rowTriples 39 24).filter (faceB sol) = R_24 := by decide +kernel
theorem face_25 : (rowTriples 39 25).filter (faceB sol) = R_25 := by decide +kernel
theorem face_26 : (rowTriples 39 26).filter (faceB sol) = R_26 := by decide +kernel
theorem face_27 : (rowTriples 39 27).filter (faceB sol) = R_27 := by decide +kernel
theorem face_28 : (rowTriples 39 28).filter (faceB sol) = R_28 := by decide +kernel
theorem face_29 : (rowTriples 39 29).filter (faceB sol) = R_29 := by decide +kernel
theorem face_30 : (rowTriples 39 30).filter (faceB sol) = R_30 := by decide +kernel
end Kobon
