/- GENERATED by tools/gen.py: rows 31..38 -/
import KobonCert.Data
namespace Kobon
theorem face_31 : (rowTriples 39 31).filter (faceB sol) = R_31 := by decide +kernel
theorem face_32 : (rowTriples 39 32).filter (faceB sol) = R_32 := by decide +kernel
theorem face_33 : (rowTriples 39 33).filter (faceB sol) = R_33 := by decide +kernel
theorem face_34 : (rowTriples 39 34).filter (faceB sol) = R_34 := by decide +kernel
theorem face_35 : (rowTriples 39 35).filter (faceB sol) = R_35 := by decide +kernel
theorem face_36 : (rowTriples 39 36).filter (faceB sol) = R_36 := by decide +kernel
theorem face_37 : (rowTriples 39 37).filter (faceB sol) = R_37 := by decide +kernel
theorem face_38 : (rowTriples 39 38).filter (faceB sol) = R_38 := by decide +kernel
end Kobon
