import LeanProject.Zipper

/-!
# Hint data for the kernel check

Zippers of `0LE1LA_1LC1RH_1RA1RF_0RF0RD_1RD1LB_1LC1RD` after 249880 and 249881 steps, generated by
`search/gen_witness_data.py`. They are only compared against the kernel's own evaluation
of `runZ`/`stepZ` (in `Witness249881.lean`); wrong data would make those checks fail and
could not produce a false theorem.
-/

namespace BB6.Witness

open BB6

/-- The zipper after 249880 steps: |l| = 3, |r| = 731, state B. -/
def zA : Z where
  l := [
    true, false, true]
  a := true
  r := [
    true, false, true, true, true, true, true, true, false, true, true, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    true, true, false, true, true, true, false, true, true, true, false, true, true, true,
    false, true, true]
  s := .B

/-- The zipper after 249881 steps: |l| = 4, |r| = 730, state H. -/
def zB : Z where
  l := [
    true, true, false, true]
  a := true
  r := [
    false, true, true, true, true, true, true, false, true, true, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true]
  s := .H

end BB6.Witness
