import re
def rows(txt):
    r=re.findall(r'^i=(\d+): (\d) (\d) (\d)$',txt,re.M)
    out=[]
    for i,(idx,a,b,c) in enumerate(r):
        if int(idx)!=len(out): break
        out.append([int(a)-1,int(b)-1,int(c)-1])
    return out
cases=[]
s=open('facts/f8e1edfe45707104.md',encoding='utf-8').read(); cases.append((4,10,rows(s[s.find('## proof'):]),'f8e1edfe45707104'))
s=open('facts/6309f733d6da8cd6.md',encoding='utf-8').read(); cases.append((6,14,rows(s[s.find('## proof'):]),'6309f733d6da8cd6'))
s=open('facts/a491fe56b9f2d831.md',encoding='utf-8').read(); s=s[s.find('## proof'):]
parts=re.split(r'=== CASE k=(\d+), period p=(\d+) ===',s)
for i in range(1,len(parts),3):
    cases.append((int(parts[i]),int(parts[i+1]),rows(parts[i+2]),'a491fe56b9f2d831'))
for k,p,t,f in cases: print(k,p,len(t)); assert len(t)==p
o=['''/-
  GPPeriodic.lean — generalized Petersen graphs GP(n,k) (general k) as cyclic block graphs, the criterion for
  periodic colourings, and the families GP(10m,4), GP(14m,6), GP(17m,8), GP(22m,10), GP(26m,12), GP(30m,14) (m ≥ 1):
  star edge colourings with 5 colours.

  GP(n,k): vertices u_i, v_i (i ∈ Z/n); edges u_i u_{i+1}, u_i v_i, v_i v_{i+k}.  Encoding: u_i = 2i, v_i = 2i+1
  in `Fin (n * 2)`; edge 3i: u_i u_{i+1}, 3i+1: u_i v_i, 3i+2: v_i v_{i+k} in `Fin (n * 3)`.
  The colourings (period L, block i gets row i mod L of the table, columns: outer, spoke, inner edge) are those of
  the star6 facts f8e1edfe45707104 (k = 4), 6309f733d6da8cd6 (k = 6), a491fe56b9f2d831 (k = 8, 10, 12, 14), colours
  shifted to 0..4.  (Generated by gen_gpper.py from the tables of these facts.)
-/
import BlockProps
import GPetersen2

namespace GPk
open BlockStar GPetersen2

def kjmp (k s : Nat) : Nat := match s with
  | 0 => 1 | 1 => 0 | _ => k

/-- wiring of GP(n,k): vertex types u = 0, v = 1; edge types 0: u_i u_{i+1}, 1: u_i v_i, 2: v_i v_{i+k} -/
def gpkWir (k : Nat) : Wir Unit 2 3 where
  D := max 1 k
  src := fun _ s => psrc s
  jmp := fun _ s => kjmp k s
  dst := fun _ s => pdst s
  hsrc := by intro w s; unfold psrc; split <;> omega
  hdst := by intro w s; unfold pdst; split <;> omega
  hjmp := by intro w s; unfold kjmp; split <;> omega
  jumps := [0, 1, k]
  hjmps := by intro w s; unfold kjmp; split <;> simp

/-- the generalized Petersen graph GP(n,k) -/
def gp (n k : Nat) : MGraph := BG (gpkWir k) n (fun _ => ())

/-- colour (0..4) of the edge type `s` in a block with pattern `c = [outer, spoke, inner]` -/
def ct (c : List Nat) (s : Nat) : Nat := (c.getD s 0) % 5

theorem ct_lt : ∀ c s, ct c s < 5 := fun _ _ => Nat.mod_lt _ (by decide)

/-- the periodic colouring with table `tab`: block `J` gets the pattern `tab[J mod tab.length]` -/
def pcol (tab : List (List Nat)) {m : Nat} : Fin m → Fin 5 :=
  bcol 3 ct ct_lt (fun J => tab.getD (J % tab.length) [])

/-- all windows of the periodic sequence pass the window check -/
abbrev perOK (k : Nat) (tab : List (List Nat)) : Prop :=
  ∀ j, j < tab.length → winOK (gpkWir k) ct (fun _ => ()) (fun p => tab.getD ((j + p) % tab.length) []) = true

/-- a periodic colouring whose windows pass the check is a star edge colouring of GP(L m, k), L the period -/
theorem periodic_star (k : Nat) (tab : List (List Nat)) (hL : 0 < tab.length) (h : perOK k tab) (m : Nat) :
    (gp (tab.length * m) k).Star 5 (pcol tab) := by
  apply star_of_windows
  intro j hj
  refine ⟨fun _ => (), fun p => tab.getD ((j % tab.length + p) % tab.length) [], ?_,
    h (j % tab.length) (Nat.mod_lt _ hL)⟩
  intro p _
  refine ⟨rfl, ?_⟩
  show tab.getD ((j % tab.length + p) % tab.length) [] = tab.getD ((j + p) % (tab.length * m) % tab.length) []
  rw [Nat.mod_mul_right_mod, Nat.mod_add_mod]

theorem gp_loopless (n k : Nat) (hk : 0 < k) (hn : max 1 k < n) : (gp n k).Loopless := by
  apply BG_loopless
  · exact hn
  · intro w s hs hz
    have hz' : kjmp k s = 0 := hz
    show psrc s ≠ pdst s
    have hs' : s < 3 := hs
    interval_cases s
    · have h1 : kjmp k 0 = 1 := rfl
      omega
    · decide
    · have h1 : kjmp k 2 = k := rfl
      omega

/-- the statement of `Families.StarFamily` (repeated here to keep the import graph small) -/
def StarFam (G : MGraph) (k : Nat) : Prop :=
  G.Subcubic ∧ G.Loopless ∧ (∀ P : Fin G.m → Prop, MGraph.Colourable P k) ∧
    (∀ P : Fin G.m → Prop, MGraph.Colourable P 6)
''']
names=[]
for k,p,t,f in cases:
    tab='['+',\n   '.join(', '.join('['+', '.join(map(str,r))+']' for r in t[i:i+6]) for i in range(0,p,6))+']'
    o.append(f'''
/-- period-{p} colouring of GP({p}m,{k}) (fact {f}) -/
def tab{k} : List (List Nat) :=
  {tab}

theorem per{k} : perOK {k} tab{k} := by decide +kernel

theorem subcubic{k} (n : Nat) : (gp n {k}).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP({p}m,{k}), m ≥ 1**: `pcol tab{k}` is a star edge colouring with 5 colours -/
theorem star{k} (m : Nat) : (gp ({p} * m) {k}).Star 5 (pcol tab{k}) :=
  periodic_star {k} tab{k} (by decide) per{k} m

theorem family{k} (m : Nat) (hm : 1 ≤ m) : StarFam (gp ({p} * m) {k}) 5 :=
  ⟨subcubic{k} _, gp_loopless _ _ (by decide) (by show max 1 {k} < {p} * m; omega),
    colourable_of_star (star{k} m) (Nat.le_refl 5), colourable_of_star (star{k} m) (by decide)⟩
''')
    names+= [f'GPk.star{k}',f'GPk.family{k}']
o.append('\nend GPk\n')
for nm in names: o.append(f'#check @{nm}')
for nm in names: o.append(f'#print axioms {nm}')
open('pack4/src/GPPeriodic.lean','w',encoding='utf-8',newline='\n').write('\n'.join(o)+'\n')
