/- GENERATED by tools/gen.py (literal numbers n = 39, count = 471) -- do not edit.
Kernel-checked facts about the concrete arrangement `sol`.  Every computation is `decide +kernel`:
the Lean kernel evaluates the Bool/Nat/List expression (exact integer arithmetic).  The heavy
part is split by rows (smallest line index) over the modules Chunk.F* / Chunk.E*. -/
import KobonCert.Data
import KobonCert.Chunk.F0
import KobonCert.Chunk.F1
import KobonCert.Chunk.F2
import KobonCert.Chunk.F3
import KobonCert.Chunk.F4
import KobonCert.Chunk.F5
import KobonCert.Chunk.F6
import KobonCert.Chunk.F7
import KobonCert.Chunk.F8
import KobonCert.Chunk.F9
import KobonCert.Chunk.F10
import KobonCert.Chunk.F11
import KobonCert.Chunk.F12
import KobonCert.Chunk.F13
import KobonCert.Chunk.F14
import KobonCert.Chunk.F15
import KobonCert.Chunk.F16
import KobonCert.Chunk.F17
import KobonCert.Chunk.F18
import KobonCert.Chunk.F19
import KobonCert.Chunk.F20
import KobonCert.Chunk.F21
import KobonCert.Chunk.E0
import KobonCert.Chunk.E1
import KobonCert.Chunk.E2
import KobonCert.Chunk.E3
import KobonCert.Chunk.E4
import KobonCert.Chunk.E5
import KobonCert.Chunk.E6
import KobonCert.Chunk.E7
import KobonCert.Chunk.E8
import KobonCert.Chunk.E9
import KobonCert.Chunk.E10
import KobonCert.Chunk.E11
import KobonCert.Chunk.E12
import KobonCert.Chunk.E13
import KobonCert.Chunk.E14
import KobonCert.Chunk.E15
import KobonCert.Chunk.E16
import KobonCert.Chunk.E17
import KobonCert.Chunk.E18
import KobonCert.Chunk.E19
import KobonCert.Chunk.E20
import KobonCert.Chunk.E21

namespace Kobon

/-- accepted by the hill: 39 proper, pairwise distinct lines, coefficients within 10^30 -/
theorem sol_valid : validB 39 sol = true := by decide +kernel

theorem sol_length : sol.length = 39 := by decide +kernel

/-- the list of triangles is strictly increasing (so it has no repeated entry) -/
theorem reportFaces_inc : incB reportFaces = true := by decide +kernel

theorem reportFaces_length : reportFaces.length = 471 := by decide +kernel

theorem range_n : List.range 39 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38] := by decide +kernel

/-- determinant ("geometric") checker: the triangular faces are exactly the reported ones -/
theorem sol_faces : faces sol = reportFaces := by
  rw [faces, sol_length, idxTriples, range_n]
  simp only [List.flatMap_cons, List.flatMap_nil, List.filter_append, List.filter_nil,
    face_0, face_1, face_2, face_3, face_4, face_5, face_6, face_7, face_8, face_9, face_10, face_11, face_12, face_13, face_14, face_15, face_16, face_17, face_18, face_19, face_20, face_21, face_22, face_23, face_24, face_25, face_26, face_27, face_28, face_29, face_30, face_31, face_32, face_33, face_34, face_35, face_36, face_37, face_38]
  rfl

/-- transcription of eval.py (consecutive vertices on each side): the same list -/
theorem sol_evalFaces : evalFaces sol = reportFaces := by
  rw [evalFaces, sol_length, idxTriples, range_n]
  simp only [List.flatMap_cons, List.flatMap_nil, List.filter_append, List.filter_nil,
    eface_0, eface_1, eface_2, eface_3, eface_4, eface_5, eface_6, eface_7, eface_8, eface_9, eface_10, eface_11, eface_12, eface_13, eface_14, eface_15, eface_16, eface_17, eface_18, eface_19, eface_20, eface_21, eface_22, eface_23, eface_24, eface_25, eface_26, eface_27, eface_28, eface_29, eface_30, eface_31, eface_32, eface_33, eface_34, eface_35, eface_36, eface_37, eface_38]
  rfl

theorem kobonCount_sol : kobonCount sol = 471 := by
  unfold kobonCount; rw [sol_faces]; exact reportFaces_length

theorem evalCount_sol : evalCount sol = 471 := by
  unfold evalCount; rw [sol_evalFaces]; exact reportFaces_length

end Kobon
