/- GENERATED by tools/gen.py (literal numbers n = 39, count = 471) -- do not edit.
Final statements. -/
import KobonCert.Cert
import KobonCert.Simple
import KobonCert.Faces

namespace Kobon

/-- T1 (combinatorial certificate): the arrangement `sol` of solution.json is a valid
submission for n = 39 and has exactly 471 triangular faces, for the determinant checker
and for the transcription of the hill evaluator; both produce the reported list. -/
theorem certificate :
    validB 39 sol = true ∧ kobonCount sol = 471 ∧ evalCount sol = 471 ∧
    faces sol = reportFaces ∧ evalFaces sol = reportFaces :=
  ⟨sol_valid, kobonCount_sol, evalCount_sol, sol_faces, sol_evalFaces⟩

/-- T2 (geometric statement for the concrete arrangement): the index triples i < j < k < 39
whose lines bound a triangular face in the sense of `IsTriFace` (real plane) are exactly
the 471 reported ones. -/
theorem sol_triFaces :
    {t : ℕ × ℕ × ℕ | t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < 39 ∧
        IsTriFace sol (nth sol t.1) (nth sol t.2.1) (nth sol t.2.2)}.ncard = 471 := by
  have h := ncard_triFaces sol (proper_of_validB sol_valid) reportFaces sol_faces reportFaces_inc
  rw [reportFaces_length, sol_length] at h
  exact h

/-- T2 (existence): there is an arrangement of 39 pairwise distinct lines in the real plane
with exactly 471 triangular faces in the sense of `IsTriFace`.  Hence K(39) ≥ 471. -/
theorem kobon_lower_bound :
    ∃ L : List Line, L.length = 39 ∧ (∀ l ∈ L, l.a ≠ 0 ∨ l.b ≠ 0) ∧
      L.Pairwise (fun p q => ¬ ∀ P : ℝ × ℝ, OnLine p P ↔ OnLine q P) ∧
      {t : ℕ × ℕ × ℕ | t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < 39 ∧
        IsTriFace L (nth L t.1) (nth L t.2.1) (nth L t.2.2)}.ncard = 471 :=
  ⟨sol, sol_length, proper_of_validB sol_valid, distinct_of_validB sol_valid, sol_triFaces⟩

/-- T2 (non-overlapping triangles; the usual meaning of K(39) ≥ 471): 39 pairwise distinct
lines in the real plane and 471 triples of them, each bounding a nondegenerate triangle
(vertices = the three pairwise intersection points) whose open interior meets none of the
39 lines; the 471 open triangles are pairwise disjoint. -/
theorem kobon_nonoverlapping :
    ∃ (L : List Line) (T : Finset (ℕ × ℕ × ℕ)) (tri : ℕ × ℕ × ℕ → (ℝ × ℝ) × (ℝ × ℝ) × (ℝ × ℝ)),
      L.length = 39 ∧ (∀ l ∈ L, l.a ≠ 0 ∨ l.b ≠ 0) ∧
      L.Pairwise (fun p q => ¬ ∀ P : ℝ × ℝ, OnLine p P ↔ OnLine q P) ∧
      T.card = 471 ∧
      (∀ t ∈ T, t.1 < t.2.1 ∧ t.2.1 < t.2.2 ∧ t.2.2 < 39 ∧
        TriWitness L (nth L t.1) (nth L t.2.1) (nth L t.2.2) (tri t).1 (tri t).2.1 (tri t).2.2) ∧
      (∀ t ∈ T, ∀ t' ∈ T, t ≠ t' →
        Disjoint (openTri (tri t).1 (tri t).2.1 (tri t).2.2)
          (openTri (tri t').1 (tri t').2.1 (tri t').2.2)) := by
  obtain ⟨T, tri, hc, h1, h2⟩ := exists_family sol (proper_of_validB sol_valid)
    (distinct_of_validB sol_valid) reportFaces sol_faces reportFaces_inc
  refine ⟨sol, T, tri, sol_length, proper_of_validB sol_valid, distinct_of_validB sol_valid,
    by rw [hc, reportFaces_length], fun t ht => ?_, h2⟩
  have h := h1 t ht
  rw [sol_length] at h
  exact h

end Kobon

#print axioms Kobon.kobon_nonoverlapping
#print axioms Kobon.triFaces_disjoint
#print axioms Kobon.certificate
#print axioms Kobon.sol_simple
#print axioms Kobon.triCheck_iff
#print axioms Kobon.sol_triFaces
#print axioms Kobon.kobon_lower_bound
