/- GENERATED by tools/gen.py -- do not edit. -/
import KobonCert.Data

namespace Kobon

/-- general position: no two lines parallel, no three lines concurrent -/
theorem sol_simple : simpleB sol = true := by decide +kernel

end Kobon
