/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesUtil

/-!
# Erdős Problem 619

*References:*
- [erdosproblems.com/619](https://www.erdosproblems.com/619)
- [EGR98] Erdős, Paul and Gyárfás, András and Ruszinkó, Miklós, *How to decrease the
  diameter of triangle-free graphs*. Combinatorica **18** (1998), 493-501.
- [Er99] Erdős, Paul, *A selection of problems and results in combinatorics*.
  Combin. Probab. Comput. **8** (1999), 1-6.
-/

@[expose] public section

open SimpleGraph

namespace Erdos619

/--
For a graph $G$, `minNewEdges r G` is the smallest number of edges that need to be added
to $G$ so that it has diameter at most $r$, while preserving the property of being
triangle-free. Erdős, Gyárfás and Ruszinkó denote this quantity by $h_r(G)$ in [EGR98].

Adding edges is formalised as passing to a supergraph `H ≥ G` on the same vertex set, the
number of added edges being the (finite) cardinality of the edge set of `H \ G`. We use
the extended diameter `SimpleGraph.ediam` (valued in `ℕ∞`) so that disconnected
supergraphs, which have infinite diameter, do not qualify. If no triangle-free supergraph
of `G` of diameter at most `r` exists, then `minNewEdges r G = 0` by the `Nat.sInf`
convention on the empty set; `erdos_619.variants.add_edges_diam_three` shows this
degenerate case does not occur for connected triangle-free `G` when `3 ≤ r`.
-/
noncomputable def minNewEdges {V : Type*} (r : ℕ) (G : SimpleGraph V) : ℕ :=
  sInf {k | ∃ H : SimpleGraph V,
    G ≤ H ∧ H.CliqueFree 3 ∧ H.ediam ≤ r ∧ (H \ G).edgeSet.ncard = k}

/--
**Erdős Problem 619** [EGR98, Er99]: For a triangle-free graph $G$ let $h_r(G)$ be the
smallest number of edges that need to be added to $G$ so that it has diameter $r$ (while
preserving the property of being triangle-free). Is it true that there exists a constant
$c>0$ such that if $G$ is a connected graph on $n$ vertices then $h_4(G)<(1-c)n$?

The answer is **no**: for every $\eta>0$ there exist connected triangle-free graphs on
$n$ vertices with $h_4(G)\geq(1-\eta)n$, so no such constant $c$ exists. The original proof
was generated by Claude Fable 5; the Lean formalization was sketched by Fable and
implemented by GPT 5.5 with Codex (see the linked `formal_proof`).
-/
@[category research solved, AMS 5,
  formal_proof using formal_conjectures at
    "https://github.com/google-deepmind/formal-conjectures/blob/b8c7a76f267c29eaa41d1212c211a920be8b05ea/FormalConjectures/ErdosProblems/619.lean#L6009",
  formal_proof using lean4 at
    "https://github.com/nick-kuhn/erdos-619/blob/7f65718b8c1019ecc24e6c9a6b04ec4c66a4e26f/Solution.lean#L5869"]
theorem erdos_619 : answer(False) ↔
    ∃ c > (0 : ℝ), ∀ (V : Type) [Fintype V] (G : SimpleGraph V),
      G.Connected → G.CliqueFree 3 →
      (minNewEdges 4 G : ℝ) < (1 - c) * Fintype.card V := by
  sorry

/-
## Partial results
-/

/--
Erdős, Gyárfás and Ruszinkó [EGR98]: every connected triangle-free graph on a finite
vertex set can be extended, by adding edges, to a triangle-free graph of diameter at
most $3$. This shows that the infimum defining `minNewEdges r G` ranges over a nonempty
set for every `3 ≤ r`.
-/
@[category research solved, AMS 5]
theorem erdos_619.variants.add_edges_diam_three {V : Type*} [Fintype V]
    (G : SimpleGraph V) (hG : G.Connected) (hG' : G.CliqueFree 3) :
    ∃ H : SimpleGraph V, G ≤ H ∧ H.CliqueFree 3 ∧ H.ediam ≤ 3 := by
  classical
  -- `H` : a maximal triangle-free supergraph of `G` (exists since `SimpleGraph V` is finite)
  obtain ⟨H, hGH, hmax⟩ :=
    (Set.toFinite {H : SimpleGraph V | H.CliqueFree 3}).exists_le_maximal hG'
  have hHcf : H.CliqueFree 3 := hmax.1
  refine ⟨H, hGH, hHcf, ?_⟩
  -- any two non-adjacent distinct vertices of `H` have a common neighbour
  have common : ∀ u v : V, u ≠ v → ¬ H.Adj u v → ∃ w, H.Adj u w ∧ H.Adj w v := by
    intro u v huv hnadj
    obtain ⟨H', hH'⟩ : ∃ H' : SimpleGraph V,
        H' = H ⊔ SimpleGraph.fromRel (fun x y => x = u ∧ y = v) := ⟨_, rfl⟩
    have hadj' : ∀ x y, H'.Adj x y →
        H.Adj x y ∨ ((x = u ∧ y = v) ∨ (x = v ∧ y = u)) := by
      intro x y h
      rw [hH', SimpleGraph.sup_adj, SimpleGraph.fromRel_adj] at h
      rcases h with h | ⟨_, ⟨h1, h2⟩ | ⟨h1, h2⟩⟩
      · exact Or.inl h
      · exact Or.inr (Or.inl ⟨h1, h2⟩)
      · exact Or.inr (Or.inr ⟨h2, h1⟩)
    have huv' : H'.Adj u v := by
      rw [hH', SimpleGraph.sup_adj, SimpleGraph.fromRel_adj]
      exact Or.inr ⟨huv, Or.inl ⟨rfl, rfl⟩⟩
    have hle : H ≤ H' := by rw [hH']; exact le_sup_left
    have hncf : ¬ H'.CliqueFree 3 := fun hcf => hnadj (hmax.2 hcf hle huv')
    -- a triangle of `H'` through the new edge gives the common neighbour
    have sub : ∀ a b c : V, ((a = u ∧ b = v) ∨ (a = v ∧ b = u)) → H'.Adj a c → H'.Adj b c →
        ∃ w, H.Adj u w ∧ H.Adj w v := by
      intro a b c hP hac hbc
      have hca : c ≠ a := hac.ne'
      have hcb : c ≠ b := hbc.ne'
      have h1 : H.Adj a c := by
        rcases hadj' a c hac with h | h
        · exact h
        · exfalso
          rcases hP with ⟨e1, e2⟩ | ⟨e1, e2⟩ <;> rcases h with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact hcb (e4.trans e2.symm)
          · exact hca (e4.trans e1.symm)
          · exact hca (e4.trans e1.symm)
          · exact hcb (e4.trans e2.symm)
      have h2 : H.Adj b c := by
        rcases hadj' b c hbc with h | h
        · exact h
        · exfalso
          rcases hP with ⟨e1, e2⟩ | ⟨e1, e2⟩ <;> rcases h with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact hcb (e4.trans e2.symm)
          · exact hca (e4.trans e1.symm)
          · exact hca (e4.trans e1.symm)
          · exact hcb (e4.trans e2.symm)
      rcases hP with ⟨e1, e2⟩ | ⟨e1, e2⟩
      · exact ⟨c, by rw [← e1]; exact h1, by rw [← e2]; exact h2.symm⟩
      · exact ⟨c, by rw [← e2]; exact h2, by rw [← e1]; exact h1.symm⟩
    by_contra hno
    apply hncf
    intro t ht
    rw [SimpleGraph.is3Clique_iff] at ht
    obtain ⟨a, b, c, hab, hac, hbc, -⟩ := ht
    rcases hadj' a b hab with h1 | h1
    · rcases hadj' a c hac with h2 | h2
      · rcases hadj' b c hbc with h3 | h3
        · exact hHcf {a, b, c} (SimpleGraph.is3Clique_iff.mpr ⟨a, b, c, h1, h2, h3, rfl⟩)
        · exact hno (sub b c a h3 hab.symm hac.symm)
      · exact hno (sub a c b h2 hab hbc.symm)
    · exact hno (sub a b c h1 hac hbc)
  -- hence `H` has diameter at most `2`
  have hdist : ∀ u v : V, H.edist u v ≤ 2 := by
    intro u v
    by_cases huv : u = v
    · rw [huv, SimpleGraph.edist_self]; simp
    · by_cases hadj : H.Adj u v
      · rw [SimpleGraph.edist_eq_one_iff_adj.mpr hadj]; exact one_le_two
      · obtain ⟨w, h1, h2⟩ := common u v huv hadj
        have hw := (SimpleGraph.Walk.cons h1 (SimpleGraph.Walk.cons h2 SimpleGraph.Walk.nil)).edist_le
        refine hw.trans ?_
        simp
  exact (SimpleGraph.ediam_le_of_edist_le hdist).trans
    (by exact_mod_cast (by norm_num : (2 : ℕ) ≤ 3))

/--
Erdős, Gyárfás and Ruszinkó [EGR98]: $h_3(G) \leq n$ for every connected triangle-free
graph $G$ on $n$ vertices.
-/
@[category research solved, AMS 5]
theorem erdos_619.variants.h_three_le {V : Type*} [Fintype V]
    (G : SimpleGraph V) (hG : G.Connected) (hG' : G.CliqueFree 3) :
    minNewEdges 3 G ≤ Fintype.card V := by
  sorry

/--
Erdős, Gyárfás and Ruszinkó [EGR98]: $h_5(G) \leq \frac{n-1}{2}$ for every connected
triangle-free graph $G$ on $n$ vertices.
-/
@[category research solved, AMS 5]
theorem erdos_619.variants.h_five_le {V : Type*} [Fintype V]
    (G : SimpleGraph V) (hG : G.Connected) (hG' : G.CliqueFree 3) :
    (minNewEdges 5 G : ℝ) ≤ (Fintype.card V - 1) / 2 := by
  sorry

/--
Erdős, Gyárfás and Ruszinkó [EGR98]: there is a constant $c > 0$ such that for every
$n$ there exist connected triangle-free graphs $G$ on $n$ vertices with
$h_3(G) \geq n - c$.
-/
@[category research solved, AMS 5]
theorem erdos_619.variants.h_three_lower :
    ∃ c > (0 : ℝ), ∀ n : ℕ, 0 < n →
      ∃ (V : Type) (_ : Fintype V) (G : SimpleGraph V),
        Fintype.card V = n ∧ G.Connected ∧ G.CliqueFree 3 ∧
        (n : ℝ) - c ≤ minNewEdges 3 G := by
  sorry

/-
## Sanity checks
-/

/-- A triangle-free graph that already has diameter at most `r` needs no new edges. -/
@[category test, AMS 5]
theorem erdos_619.test.minNewEdges_eq_zero {V : Type*} {r : ℕ} {G : SimpleGraph V}
    (hG : G.CliqueFree 3) (hdiam : G.ediam ≤ r) :
    minNewEdges r G = 0 :=
  Nat.sInf_eq_zero.mpr <| Or.inl ⟨G, le_rfl, hG, hdiam, by simp⟩

/-- The graph with a single vertex is triangle-free and has diameter `0`, so it needs no
new edges to reach diameter at most `4`. -/
@[category test, AMS 5]
theorem erdos_619.test.minNewEdges_singleton :
    minNewEdges 4 (⊥ : SimpleGraph (Fin 1)) = 0 :=
  erdos_619.test.minNewEdges_eq_zero (cliqueFree_bot (by norm_num))
    (by simp [ediam_eq_zero_of_subsingleton])

end Erdos619

#print axioms Erdos619.erdos_619.variants.add_edges_diam_three
