-- GENERATED by pack5/gen5.py from the pack3 sources; do not edit by hand (edit gen5.py).
/-
  Star6Bounded.lean — the reductions of the star6 chain restricted to bounded order.

  The library proves `ex1red`, `iic_of`, `dmsI_all`, `dms_of_I_II` with the global hypotheses (H) = `Hyp` and
  (II_D) = `IID`.  Here the same inductions are run with the hypotheses restricted to graphs with at most `N`
  vertices (`HypLE N`, `IIDLE N`); the conclusions are then restricted to order at most `N`.
  The proofs are the library proofs, copied by gen5.py with the replacements listed there:
    * ex1red_step body = MhFact_341b6e5e1be16205.lean lines 797-910 (proof of `ex1red`), 1 replacement
    * Cut2.twoSided_all_le = MhFact_90b4662cdeba097d.lean lines 13-21 (`Cut2.twoSided_all`), 2 replacements
    * iic_le = MhFact_90b4662cdeba097d.lean lines 96-159 (`iic_of`), 7 replacements
    * supp_le = MhFact_90b4662cdeba097d.lean lines 162-173 (`iiToDMSII_c`), 2 replacements
    * dmsI_all_le = MhFact_90b4662cdeba097d.lean lines 295-325 (`dmsI_all`), 5 replacements
    * minimal_impossible_le = MhFact_974f7197c1be8069.lean lines 28-180 (`DmsIILean.minimal_impossible'`), 4 replacements
  New text: `cntF_le_n`, `vcount_le_n`, `vcount_mono`, the four definitions, the statements, and `ex1red_le`.
-/
import MhFact_90b4662cdeba097d

namespace RH2F
open MGraph
open Classical

/-- the counting function is at most `n` -/
theorem cntF_le_n : ∀ (n : Nat) (W : Fin n → Prop), cntF n W ≤ n
  | 0, _ => Nat.le_refl 0
  | n + 1, W => by
    rw [cntF_succ]
    have := cntF_le_n n (fun i => W (Fin.castSucc i))
    split <;> omega

/-- an edge set has at most as many vertices as the ambient multigraph -/
theorem vcount_le_n {X : MGraph} (P : Fin X.m → Prop) : vcount P ≤ X.n := cntF_le_n _ _

/-- the vertex count is monotone in the edge set -/
theorem vcount_mono {X : MGraph} {P Q : Fin X.m → Prop} (h : ∀ f, P f → Q f) : vcount P ≤ vcount Q :=
  cntF_mono _ _ _ (fun _ ⟨f, hf, hv⟩ => ⟨f, h f hf, hv⟩)

/-- (H) restricted to at most `N` vertices: every 2-cut-reduced connected bridgeless loopless cubic multigraph with
    between 10 and `N` vertices is EX1-good -/
def HypLE (N : Nat) : Prop :=
  ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → 10 ≤ vcount P → vcount P ≤ N → TwoCutReducedOn P → EX1On P

/-- (II_D) restricted to at most `N` vertices -/
def IIDLE (N : Nat) : Prop :=
  ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → 6 ≤ vcount P → vcount P ≤ N → TwoCutReducedOn P → ∀ g, P g →
    (∀ h, P h → h ≠ g → ¬ X.Joins h (X.ends g).1 (X.ends g).2) → (∀ S, TwoCut P S → ¬ Crosses P S g) →
    Colourable (leafSet P g) 6

/-- the leaf case for all connected bridgeless cubic hosts with at most `N` vertices -/
def IIcLE (N : Nat) : Prop :=
  ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → vcount P ≤ N → ∀ g, P g → Colourable (leafSet P g) 6

/-- star 6-colourability of all connected bridgeless cubic loopless multigraphs with at most `N` vertices -/
def CubicLE (N : Nat) : Prop :=
  ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → vcount P ≤ N → Colourable P 6

section red
variable {X : MGraph} {P : Fin X.m → Prop}

/-- **The induction step of Theorem EX1-RED, unconditionally**: a connected bridgeless loopless cubic multigraph `P`
    with at least 10 vertices that is *not* 2-cut-reduced is EX1-good as soon as all smaller ones (with at least 10
    vertices) are.  (The proof of `ex1red` with its induction hypothesis made explicit; the hypothesis (H) is not
    used in this branch except on a smaller graph.) -/
theorem ex1red_step (hPS : PStat) (hSF : SmallFacts) (hG : InG X P) (n : Nat) (hn : vcount P = n) (h10 : 10 ≤ n)
    (IH : ∀ (Y : MGraph) (Q : Fin Y.m → Prop), InG Y Q → 10 ≤ vcount Q → vcount Q < n → EX1On Q)
    (hred : ¬ TwoCutReducedOn P) : EX1On P := by
  have hbig : ∃ S, BigCut P S := by
    simp only [TwoCutReducedOn, not_forall] at hred
    obtain ⟨S, hS, hno⟩ := hred
    obtain ⟨C, rfl⟩ := cut2_of_twoCut hG hS
    refine ⟨C.S, hS, C.side_ge4 hPS hG (fun h => hno (Or.inl h)), ?_⟩
    have := C.flip.side_ge4 hPS hG (by rw [scount_flip]; exact fun h => hno (Or.inr h))
    rwa [scount_flip] at this
  obtain ⟨S0, hS0, hmin⟩ := exists_min_nat (BigCut P) (fun S => scount P S true) hbig
  obtain ⟨C, rfl⟩ := cut2_of_twoCut hG hS0.1
  have hA4 : 4 ≤ scount P C.S true := hS0.2.1
  have hB4 : 4 ≤ scount P C.S false := hS0.2.2
  -- the minimal side is not larger than the other side
  have hAB : scount P C.S true ≤ scount P C.S false := by
    have := hmin C.flip.S ⟨C.flip.twoCut_self, by rw [scount_flip]; exact hB4, by rw [scount_flip]; exact hA4⟩
    rw [scount_flip] at this; exact this
  have hn' : n = scount P C.S true + scount P C.S false := by rw [← hn]; exact vcount_split P C.S
  have evA := C.side_even hPS hG
  have evB : scount P C.S false % 2 = 0 := by have := C.flip.side_even hPS hG; rwa [scount_flip] at this
  -- (m1), (m2) and the closures
  have m1b := C.m1 hG hB4
  have m1a : ∀ f f', P f → P f' → X.Joins f C.a1 C.a2 → X.Joins f' C.a1 C.a2 → f = f' :=
    C.flip.m1 hG (by rw [scount_flip]; exact hA4)
  have m2 := C.m2 hPS hG hmin hB4
  have GA := C.clo_inG hG
  have GB := C.flip.clo_inG hG
  have GDA := C.cloD_inG hG
  have GDB := C.flip.cloD_inG hG
  have vA : vcount C.clo = scount P C.S true := C.vcount_clo
  have vB : vcount C.flip.clo = scount P C.S false := by rw [C.flip.vcount_clo, scount_flip]; rfl
  have vDA : vcount C.cloD = scount P C.S true + 2 := C.vcount_cloD
  have vDB : vcount C.flip.cloD = scount P C.S false + 2 := by rw [C.flip.vcount_cloD, scount_flip]; rfl
  -- the gluing lemmas
  have twoC : EX1On C.clo → EX1On C.flip.clo → ((∃ r, P r ∧ X.Joins r C.b1 C.b2) → EX1On C.cloD) →
      ((∃ r, P r ∧ X.Joins r C.a1 C.a2) → EX1On C.flip.cloD) → EX1On P :=
    fun h1 h2 h3 h4 => ex1_2c'' hPS C hG m1a m1b h1 h2 h3 h4
  have srA : C.RecipeD → EX1On C.flip.cloD → EX1On P := fun h1 h2 => C.sr_a hPS hG h1 h2
  have srB : C.RecipeE → EX1On C.flip.clo → EX1On P := fun h1 h2 => C.sr_b hPS hG m1b h1 h2
  have srA' : C.flip.RecipeD → EX1On C.cloD → EX1On P := fun h1 h2 =>
    C.flip.sr_a hPS hG h1 (ex1On_congr (fun i => (C.flip_flip_cloD i).symm) h2)
  have srB' : C.flip.RecipeE → EX1On C.clo → EX1On P := fun h1 h2 =>
    C.flip.sr_b hPS hG m1a h1 (ex1On_congr (fun i => (C.flip_flip_clo i).symm) h2)
  have sB : ∀ k, scount P C.flip.S true = k ↔ scount P C.S false = k := fun k => by rw [scount_flip]; rfl
  by_cases hA10 : 10 ≤ scount P C.S true
  · -- Case 1: both sides have at least 10 vertices
    exact twoC (IH _ _ GA (by omega) (by omega)) (IH _ _ GB (by omega) (by omega)) (fun _ => IH _ _ GDA (by omega) (by omega))
      (fun _ => IH _ _ GDB (by omega) (by omega))
  by_cases hB10 : 10 ≤ scount P C.S false
  · -- Case 2: `|A| ∈ {4, 6, 8}`, `|B| ≥ 10`
    have CGB : EX1On C.flip.clo := IH _ _ GB (by omega) (by omega)
    have DGB : EX1On C.flip.cloD := IH _ _ GDB (by omega) (by omega)
    by_cases hCGA : EX1On C.clo
    · by_cases hr : ∃ r, P r ∧ X.Joins r C.b1 C.b2
      · by_cases hDGA : EX1On C.cloD
        · exact twoC hCGA CGB (fun _ => hDGA) (fun _ => DGB)
        · -- (2c): `|A| = 4`
          have h4 : scount P C.S true = 4 := by
            apply Classical.byContradiction
            intro h4
            have h68 : scount P C.S true = 6 ∨ scount P C.S true = 8 := by omega
            rcases h68 with h6 | h8
            · exact hDGA (hSF.s2 _ _ C hG h6)
            · exact hDGA (IH _ _ GDA (by omega) (by omega))
          rcases (hSF.s3 _ _ C hG h4).2 with hD | hE
          · exact srA hD DGB
          · exact srB hE CGB
      · exact twoC hCGA CGB (fun h => absurd h hr) (fun _ => DGB)
    · -- (2b)
      exact srA (hSF.s4 _ _ C hG (by omega) hCGA).1 DGB
  · -- Case 3: `|A| ≤ |B| ≤ 8`
    have DG6 : ∀ (D : Cut2 P), scount P D.S true = scount P C.S true ∨ scount P D.S true = scount P C.S false →
        (scount P D.S true = 6 ∨ scount P D.S true = 8) → EX1On D.cloD := by
      intro D hD h68
      rcases h68 with h6 | h8
      · exact hSF.s2 _ _ D hG h6
      · have hv := D.vcount_cloD
        exact IH _ _ (D.cloD_inG hG) (by omega) (by omega)
    have DGA : scount P C.S true ≠ 4 → EX1On C.cloD := fun h => DG6 C (Or.inl rfl) (by omega)
    have DGB : scount P C.S false ≠ 4 → EX1On C.flip.cloD := fun h =>
      DG6 C.flip (Or.inr ((sB _).2 rfl))
        (by rw [scount_flip]; show scount P C.S false = 6 ∨ scount P C.S false = 8; omega)
    by_cases hCGA : EX1On C.clo
    · by_cases hCGB : EX1On C.flip.clo
      · by_cases h3a : ((∃ r, P r ∧ X.Joins r C.b1 C.b2) → EX1On C.cloD) ∧
            ((∃ r, P r ∧ X.Joins r C.a1 C.a2) → EX1On C.flip.cloD)
        · -- (3a)
          exact twoC hCGA hCGB h3a.1 h3a.2
        · -- (3d)
          by_cases hfirst : (∃ r, P r ∧ X.Joins r C.b1 C.b2) → EX1On C.cloD
          · exfalso
            have hsecond : ¬ ((∃ r, P r ∧ X.Joins r C.a1 C.a2) → EX1On C.flip.cloD) := fun h => h3a ⟨hfirst, h⟩
            have hB4' : scount P C.S false = 4 := by
              apply Classical.byContradiction; intro h; exact hsecond (fun _ => DGB h)
            omega
          · have hA4' : scount P C.S true = 4 := by
              apply Classical.byContradiction; intro h; exact hfirst (fun _ => DGA h)
            rcases (hSF.s3 _ _ C hG hA4').2 with hD | hE
            · exact srA hD (DGB (by omega))
            · exact srB hE hCGB
      · -- (3c): side `B` is in BAD
        obtain ⟨hDB, hB6⟩ := hSF.s4 _ _ C.flip hG (by rw [scount_flip]; show scount P C.S false ≤ 8; omega) hCGB
        rw [scount_flip] at hB6
        by_cases hDGA : EX1On C.cloD
        · exact srA' hDB hDGA
        · have hA4' : scount P C.S true = 4 := by
            apply Classical.byContradiction; intro h; exact hDGA (DGA h)
          by_cases hRDA : C.RecipeD
          · exact srA hRDA (DGB (by show ¬ _ = 4; omega))
          · by_cases hB8 : scount P C.S false = 8
            · exact srB' (hSF.s5 _ _ C.flip hG ((sB 8).2 hB8) hCGB) hCGA
            · have hB6' : scount P C.S false = 6 := by show _ = 6; omega
              exact hSF.tabc _ _ C hG hA4' hB6' hCGB hDGA hRDA
    · -- (3b): side `A` is in BAD
      obtain ⟨hDA, hA6⟩ := hSF.s4 _ _ C hG (by omega) hCGA
      exact srA hDA (DGB (by omega))

end red

/-- **Theorem EX1-RED for bounded order**: (H) for at most `N` vertices gives EX1-goodness of every connected
    bridgeless loopless cubic multigraph with between 10 and `N` vertices -/
theorem ex1red_le (N : Nat) (hPS : PStat) (hSF : SmallFacts) (hH : HypLE N) :
    ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → 10 ≤ vcount P → vcount P ≤ N → EX1On P := by
  suffices h : ∀ n, ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → vcount P = n → 10 ≤ n → n ≤ N → EX1On P from
    fun X P hG h10 hN => h _ X P hG rfl h10 hN
  intro n
  induction n using Nat.strongRecOn with
  | _ n ih =>
  intro X P hG hn h10 hN
  by_cases hred : TwoCutReducedOn P
  · exact hH X P hG (by omega) (by omega) hred
  · exact ex1red_step hPS hSF hG n hn h10 (fun Y Q hGQ h1 h2 => ih _ h2 Y Q hGQ rfl h1 (by omega)) hred

section ii4
variable {X : MGraph} {P : Fin X.m → Prop}

set_option backward.isDefEq.respectTransparency false in
/-- every side with at least 4 vertices is 2-sided, under (H) for at most `N` vertices -/
theorem Cut2.twoSided_all_le (N : Nat) (hH : HypLE N) (C : Cut2 P) (hG : InG X P) (hN : vcount P ≤ N)
    (h4 : 4 ≤ scount P C.S true) :
    C.TwoSided := by
  by_cases h8 : scount P C.S true ≤ 8
  · exact C.small2sided hG h4 h8
  · have hev := C.side_even RH2P.pstat hG
    have h10 : 10 ≤ vcount C.clo := by rw [C.vcount_clo]; omega
    have hsp := vcount_split P C.S
    have hle : vcount C.clo ≤ N := by rw [C.vcount_clo]; omega
    have hex := ex1red_le N RH2P.pstat smallFacts hH _ _ (C.clo_inG hG) h10 hle
    exact C.twoSided_of_ex1 RH2P.pstat hG (C.flip.m1 hG (by rw [scount_flip]; exact h4)) hex

set_option backward.isDefEq.respectTransparency false in
/-- the leaf case for connected hosts with at most `N` vertices, from (H) and (II_D) for at most `N` vertices -/
theorem iic_le (N : Nat) (hH : HypLE N) (hD : IIDLE N) : IIcLE N := by
  suffices h : ∀ n, ∀ (X : MGraph) (P : Fin X.m → Prop), InG X P → vcount P = n → n ≤ N → ∀ g, P g →
      Colourable (leafSet P g) 6 from fun X P hG hN g hg => h _ X P hG rfl hN g hg
  intro n
  induction n using Nat.strongRecOn with
  | _ n ih =>
  intro X P hG hn hN g hg
  have hpos : 0 < vcount P := cntF_le_of_mem _ _ (i := (X.ends g).1) ⟨g, hg, Or.inl rfl⟩
  by_cases hsmall : n ≤ 4
  · exact step2 hG hpos (by omega) hg
  have hev := vcount_even RH2P.pstat hG
  -- Step 3: a reducible 2-edge-cut
  by_cases hred : ∃ S, TwoCut P S ∧ ¬ (S (X.ends g).1 = true ∧ S (X.ends g).2 = true) ∧ 4 ≤ scount P S true
  · obtain ⟨S, hS, hgS, h4⟩ := hred
    obtain ⟨C, rfl⟩ := cut2_of_twoCut hG hS
    have hts := C.twoSided_all_le N hH hG (by omega) h4
    have hsplit := vcount_split P C.S
    have hvB : vcount C.flip.clo < n := by rw [C.flip.vcount_clo, scount_flip]; simp; omega
    rcases C.cases_P hg with hA | hB | hcut
    · exact absurd ⟨hA.2.1, hA.2.2⟩ hgS
    · exact C.leaf_glue_B hG.1 hG.2.2.2 hB hts
        (ih _ hvB _ _ (C.flip.clo_inG hG) rfl (by omega) _ (Or.inr ⟨g, rfl, hB⟩))
    · rcases hcut with rfl | rfl
      · exact C.leaf_glue_E hG.1 hG.2.2.2 hts (ih _ hvB _ _ (C.flip.clo_inG hG) rfl (by omega) _ (Or.inl rfl))
      · have hvB' : vcount C.swap12.flip.clo < n := by
          rw [C.swap12.flip.vcount_clo, scount_flip]; simp; exact (by rw [C.flip.vcount_clo, scount_flip] at hvB; first | simpa using hvB | exact hvB | (simp at hvB; exact hvB))
        exact C.swap12.leaf_glue_E hG.1 hG.2.2.2 (C.swap12_twoSided hts)
          (ih _ hvB' _ _ (C.swap12.flip.clo_inG hG) rfl (by omega) _ (Or.inl rfl))
  -- Step 4: every 2-edge-cut side not containing `g` has 2 vertices
  have hnot : ∀ S, TwoCut P S → ¬ (S (X.ends g).1 = true ∧ S (X.ends g).2 = true) → scount P S true = 2 := by
    intro S hS hgS
    have h1 : scount P S true < 4 := by
      apply Classical.byContradiction; intro h; exact hred ⟨S, hS, hgS, by omega⟩
    have := twoCut_even RH2P.pstat hG hS
    have := twoCut_pos hG hS true
    omega
  have hn6 : 6 ≤ vcount P := by omega
  apply hD X P hG hn6 (by omega)
  · -- (a) 2-cut-reduced
    intro S hS
    by_cases hin : S (X.ends g).1 = true ∧ S (X.ends g).2 = true
    · obtain ⟨C, rfl⟩ := cut2_of_twoCut hG hS
      have h2 := hnot C.flip.S C.flip.twoCut_self (by rw [Cut2.flip_S, Cut2.flip_S, hin.1, hin.2]; simp)
      rw [scount_flip] at h2
      exact Or.inr h2
    · exact Or.inl (hnot S hS hin)
  · exact hg
  · -- (b) no edge parallel to `g`
    intro h hh hne hj
    obtain ⟨S, hS, hSs, hcount⟩ := digon_cut hG (by omega) hg hh hne hj
    have := hnot S hS (fun h' => by rw [hSs] at h'; exact absurd h'.1 (by decide))
    omega
  · -- (c) `g` in no 2-edge-cut
    intro S hS hcr
    obtain ⟨C, rfl⟩ := cut2_of_twoCut hG hS
    have hd := hcr.2
    have h1 := hnot C.S hS (fun h' => hd (h'.1.trans h'.2.symm))
    have h2 := hnot C.flip.S C.flip.twoCut_self (fun h' => by
      rw [Cut2.flip_S, Cut2.flip_S] at h'
      exact hd (by cases h1' : C.S (X.ends g).1 <;> cases h2' : C.S (X.ends g).2 <;> simp_all))
    rw [scount_flip] at h2
    have := vcount_split P C.S
    simp at h2
    omega

set_option backward.isDefEq.respectTransparency false in
/-- the suppression configuration over a host with at most `N` vertices -/
theorem supp_le (N : Nat) (hII : IIcLE N) (G : MGraph) (Q : Fin G.m → Prop) (S : SuppData Q) (hloop : Loopless G)
    (huw : S.u ≠ S.w) (hC : ConnectedOn (supp Q S.y S.u S.w)) (hB : BridgelessOn (supp Q S.y S.u S.w))
    (hK : CubicOn (supp Q S.y S.u S.w)) (hN : G.n ≤ N) : Colourable Q 6 := by
  have hXl : Loopless (addEdge G S.u S.w) := by
    intro f
    by_cases h : f.val < G.m
    · have := hloop ⟨f.val, h⟩
      simpa [addEdge, h] using this
    · simp [addEdge, h]; exact huw
  obtain ⟨c', hc'⟩ := hII (addEdge G S.u S.w) (supp Q S.y S.u S.w) ⟨hXl, hC, hB, hK⟩
    (by have := vcount_le_n (supp Q S.y S.u S.w); have : (addEdge G S.u S.w).n = G.n := rfl; omega)
    (Fin.last G.m) (Or.inl rfl)
  exact ⟨fun a => c' (psiT S a), starOn_embed (phiT S) (psiT S)
    (fun x y _ _ _ _ _ _ h => phiT_inj S x y h) (fun a b ha hb h => psiT_inj S a b ha hb h)
    (fun a ha => psiT_set S a ha) (fun a ha => psiT_joins S hloop a ha) hc'⟩

set_option backward.isDefEq.respectTransparency false in
/-- (I) for all bridgeless loopless cubic multigraphs with at most `N` vertices -/
theorem dmsI_all_le (N : Nat) (hH : HypLE N) : ∀ (X : MGraph) (P : Fin X.m → Prop), Loopless X → BridgelessOn P →
    CubicOn P → vcount P ≤ N → Colourable P 6 := by
  suffices h : ∀ n, ∀ (X : MGraph) (P : Fin X.m → Prop), Loopless X → BridgelessOn P → CubicOn P → vcount P = n → n ≤ N →
      Colourable P 6 from fun X P hL hB hK hN => h _ X P hL hB hK rfl hN
  intro n
  induction n using Nat.strongRecOn with
  | _ n ih =>
  intro X P hL hB hK hn hN
  by_cases hne : ∃ g, P g
  · obtain ⟨g, hg⟩ := hne
    let s := (X.ends g).1
    have hs : meets P s := ⟨g, hg, Or.inl rfl⟩
    -- the component of `s`
    have hGK : InG X (compK P s) := ⟨hL, compK_connected s, cut_of_part hB s True (compK_iff s),
      cubic_of_part hK s True (compK_iff s)⟩
    have hcK : Colourable (compK P s) 6 := by
      by_cases h10 : 10 ≤ vcount (compK P s)
      · have hmono := vcount_mono (P := compK P s) (Q := P) (fun f hf => hf.1)
        have hex := ex1red_le N RH2P.pstat smallFacts hH _ _ hGK h10 (by omega)
        have hgK : compK P s g := ⟨hg, reach_self s⟩
        obtain ⟨_, _, _, c, hc, _⟩ := hex g hgK true (RH2P.pstat _ _ hGK g hgK true)
        exact ⟨c, hc⟩
      · have := vcount_even RH2P.pstat hGK
        exact b8s _ _ hGK (by omega)
    have hcR : Colourable (compR P s) 6 :=
      ih _ (by rw [← hn]; exact vcount_compR s hs) X _ hL (cut_of_part hB s False (compR_iff s))
        (cubic_of_part hK s False (compR_iff s)) rfl (by have := vcount_compR (P := P) s hs; omega)
    apply colourable_of_sides (fun f => decide (Reach P s (X.ends f).1))
      (fun a b x ha hb _ hax hbx => edge_side ha hb hax hbx)
    · exact colourable_congr (fun f => by simp [compK]) hcK
    · exact colourable_congr (fun f => by simp [compR]) hcR
  · exact ⟨fun _ => 0, fun a _ _ ha _ => absurd ⟨a, ha⟩ hne, fun w h1 _ _ _ => absurd ⟨w.e1, h1⟩ hne⟩

end ii4

end RH2F

namespace RH2F
open MGraph DmsIILean

variable {G : MGraph}

/-- the minimal-counterexample argument of `DmsIILean.dms_of_I_II` for an ambient multigraph `G` with `2 * G.n ≤ N`
    (the doubling step uses a cubic multigraph on `2 * G.n` vertices) -/
theorem minimal_impossible_le (N : Nat) (hI : CubicLE N) (hII : IIcLE N) (hsub : Subcubic G) (hloop : Loopless G)
    (hN : 2 * G.n ≤ N) {Q : Fin G.m → Prop} (hmin : MinimalCounterexample Q 6) : False := by
  classical
  have hconn : ConnectedOn Q := minimal_connected hmin
  have hcoreconn : ConnectedOn (Core Q) := minimal_core_connected hmin
  have hcut : ∀ f, Core Q f → G.CutOn Q f → False := fun f hf B => core_no_cut hsub Q hmin hf B
  -- the far end of the edge at a vertex of degree one meets the core
  have hleaf : ∀ l p y, QDeg1 Q l → Q p → G.Joins p l y → ∃ f, Core Q f ∧ G.Inc f y := by
    intro l p y hl hp hj
    have hpp : Pendant Q p := pendant_of_deg1 hl hp (joins_inc_left hj)
    obtain ⟨l', y', hj', hleaf', f, g, hf, hg, hfp, hgp, hfg, hfy, hgy⟩ := pendant_attach hsub hmin hpp
    rcases joins_unique hj' hj with ⟨_, h2⟩ | ⟨_, h2⟩
    · exact ⟨f, hf, h2 ▸ hfy⟩
    · exfalso
      obtain ⟨a, _, _, ha⟩ := hl
      exact hfp ((ha f hf.1 (h2 ▸ hfy)).trans (ha p hp (joins_inc_left hj)).symm)
  have hdeg2 : ∀ x, QDeg2 Q x → ∃ f, Core Q f ∧ G.Inc f x := by
    intro x hx
    obtain ⟨a, b, hQa, hQb, hax, hbx, hab, habd⟩ := id hx
    by_cases hac : Core Q a
    · exact ⟨a, hac, hax⟩
    · have hpa : Pendant Q a := Classical.byContradiction fun hp => hac ⟨hQa, hp⟩
      obtain ⟨z, haz, hz1⟩ := deg1_of_pendant hpa
      have hzx : z ≠ x := fun h => qdeg1_not2 (h ▸ hz1) hx
      exact hleaf z a x hz1 hQa (joins_of_inc_ne haz hax hzx)
  -- `Q` has an edge
  obtain ⟨e0, he0⟩ : ∃ f, Q f := by
    apply Classical.byContradiction
    intro h
    apply hmin.1
    exact ⟨fun _ => 0, fun a _ _ ha _ => absurd ⟨a, ha⟩ h, fun w h1 _ _ _ => absurd ⟨w.e1, h1⟩ h⟩
  -- the core edges are the edges of `Q` whose ends both have degree three
  have core_of_deg3 : ∀ f, Q f → (∀ x, G.Inc f x → QDeg3 Q x) → Core Q f := by
    intro f hf h3
    refine ⟨hf, fun hp => ?_⟩
    obtain ⟨x, hfx, hx1⟩ := deg1_of_pendant hp
    exact qdeg1_not3 hx1 (h3 x hfx)
  by_cases hR0 : ∃ r, QDeg1 Q r ∨ QDeg2 Q r
  · by_cases hR2 : ∃ r1 r2, r1 ≠ r2 ∧ (QDeg1 Q r1 ∨ QDeg2 Q r1) ∧ (QDeg1 Q r2 ∨ QDeg2 Q r2)
    · -- two vertices of degree ≤ 2: double `Q`
      obtain ⟨r1, r2, hr, hr1, hr2⟩ := hR2
      have hL := dbl.loopless hloop
      have hC := dblP_connected hconn hr1
      have hB := dblP_bridgeless hcoreconn hcut hleaf hdeg2 hr hr1 hr2
      have hK := dblP_cubic hsub Q
      obtain ⟨c, hc⟩ : Colourable (dblP Q) 6 := by
        by_cases hiso : IsoTo k33 (dblP Q)
        · exact k33_colourable hiso
        · exact hI (dbl G) (dblP Q) ⟨hL, hC, hB, hK⟩
            (by have := vcount_le_n (dblP Q); have : (dbl G).n = G.n + G.n := rfl; omega)
      apply hmin.1
      exact ⟨_, starOn_embed (G := G) (H := dbl G) (Q := Q) (P := dblP Q) dbl.vo dbl.eo
        (fun _ _ _ _ _ _ _ _ h => dbl.vo_inj h) (fun _ _ _ _ h => dbl.eo_inj h) (fun _ ha => dblP_eo.2 ha)
        (fun a _ => dbl.joins_eo (joins_ends a)) hc⟩
    · -- exactly one vertex `r` of degree ≤ 2: suppress it
      obtain ⟨r, hr⟩ := hR0
      have huniq : ∀ r', (QDeg1 Q r' ∨ QDeg2 Q r') → r' = r := fun r' hr' =>
        Classical.byContradiction fun hne => hR2 ⟨r', r, hne, hr', hr⟩
      have deg3_of : ∀ x, x ≠ r → (∃ f, Q f ∧ G.Inc f x) → QDeg3 Q x := by
        intro x hxr hx
        rcases qdeg_cases hsub Q hx with h1 | h2 | h3
        · exact absurd (huniq x (Or.inl h1)) hxr
        · exact absurd (huniq x (Or.inr h2)) hxr
        · exact h3
      have hS : Nonempty (SuppData Q) := by
        rcases hr with h1 | h2
        · -- `r` is a leaf `l` with pendant edge `p = l y`
          obtain ⟨p, hp, hpl, hpall⟩ := id h1
          obtain ⟨y, hjy⟩ := exists_joins_of_inc hpl
          have hjp : G.Joins p r y := joins_symm hjy
          have hyr : y ≠ r := Ne.symm (ne_of_joins hloop hjp)
          have hy3 : QDeg3 Q y := deg3_of y hyr ⟨p, hp, joins_inc_right hjp⟩
          obtain ⟨x1, x2, hQx1, hQx2, hx1y, hx2y, hx12, hx1p, hx2p, hally⟩ :=
            three_minus_one hy3 hp (joins_inc_right hjp)
          obtain ⟨u, hju⟩ := exists_joins_of_inc hx1y
          obtain ⟨w, hjw⟩ := exists_joins_of_inc hx2y
          have hru : r ≠ u := fun h => hx1p (hpall x1 hQx1 (h ▸ joins_inc_left hju))
          have hrw : r ≠ w := fun h => hx2p (hpall x2 hQx2 (h ▸ joins_inc_left hjw))
          exact ⟨
            { y := y, u := u, w := w, l := r, f1 := x1, f2 := x2
              hf1 := joins_symm hju, hf2 := joins_symm hjw, hQ1 := hQx1, hQ2 := hQx2, hf12 := hx12
              hy := fun d hd hdy => by
                rcases hally d hd hdy with h | h | h
                · exact Or.inr (Or.inr (h ▸ joins_symm hjp))
                · exact Or.inl h
                · exact Or.inr (Or.inl h)
              hl := fun d d' hd hjd hd' hd'l =>
                (hpall d' hd' hd'l).trans (hpall d hd (joins_inc_right hjd)).symm
              hlu := hru, hlw := hrw
              hlleaf := Or.inr fun d hd hdl => (hpall d hd hdl) ▸ joins_symm hjp
              hrest := fun x hxy hxl hx => deg3_of x hxl hx }⟩
        · -- `r` is a vertex `y` of degree two
          obtain ⟨a, b, hQa, hQb, hay, hby, hab, habd⟩ := id h2
          obtain ⟨u, hju⟩ := exists_joins_of_inc hay
          obtain ⟨w, hjw⟩ := exists_joins_of_inc hby
          exact ⟨
            { y := r, u := u, w := w, l := r, f1 := a, f2 := b
              hf1 := joins_symm hju, hf2 := joins_symm hjw, hQ1 := hQa, hQ2 := hQb, hf12 := hab
              hy := fun d hd hdy => by
                rcases habd d hd hdy with h | h
                · exact Or.inl h
                · exact Or.inr (Or.inl h)
              hl := fun d _ _ hjd _ _ => absurd rfl (ne_of_joins hloop hjd)
              hlu := ne_of_joins hloop (joins_symm hju)
              hlw := ne_of_joins hloop (joins_symm hjw)
              hlleaf := Or.inl rfl
              hrest := fun x hxy _ hx => deg3_of x hxy hx }⟩
      obtain ⟨S⟩ := hS
      have hyl3 : ∀ x, x ≠ S.y → x ≠ S.l → (∃ f, Q f ∧ G.Inc f x) → QDeg3 Q x := S.hrest
      -- edges of `Q` avoiding `y` are core edges
      have coreNotY : ∀ f, Q f → ¬ G.Inc f S.y → Core Q f := by
        intro f hf hfy
        apply core_of_deg3 f hf
        intro x hfx
        have := S.not_l_of_not_y hf hfy hfx
        exact hyl3 x this.1 this.2 ⟨f, hf, hfx⟩
      have hcutQ' : ∀ f, Q f → ¬ G.Inc f S.y → G.CutOn Q f → False :=
        fun f hf hfy B => hcut f (coreNotY f hf hfy) B
      have huw : S.u ≠ S.w := S.u_ne_w hloop hcutQ'
      have hyw := S.y_ne_w hloop
      have hf2core : Core Q S.f2 := by
        have hw3 : QDeg3 Q S.w := hyl3 S.w (Ne.symm hyw) (Ne.symm S.hlw) ⟨S.f2, S.hQ2, joins_inc_right S.hf2⟩
        obtain ⟨x1, _, hQx1, _, hx1w, _, _, hx1f, _, _⟩ := three_minus_one hw3 S.hQ2 (joins_inc_right S.hf2)
        exact ⟨S.hQ2, not_pendant_of_two S.hf2 S.hQ1 S.hf12 (joins_inc_left S.hf1) hQx1 hx1f hx1w⟩
      have hcutQ'' : ∀ f, Q f → (f = S.f2 ∨ ¬ G.Inc f S.y) → G.CutOn Q f → False := by
        intro f hf hcase B
        rcases hcase with rfl | hfy
        · exact hcut _ hf2core B
        · exact hcut f (coreNotY f hf hfy) B
      have hL := addEdge_loopless hloop huw
      have hC := S.supp_connected hloop hconn
      have hB := S.supp_bridgeless hloop hcutQ''
      have hK := S.supp_cubic hloop huw
      apply hmin.1
      by_cases hiso : IsoTo k33 (supp Q S.y S.u S.w)
      · exact k33_supp_colourable hloop S hiso
      · exact supp_le N hII G Q S hloop huw hC hB hK (by omega)
  · -- no vertex of degree ≤ 2: `Q` itself is cubic
    have hK : CubicOn Q := by
      intro x hx
      rcases qdeg_cases hsub Q hx with h1 | h2 | h3
      · exact absurd ⟨x, Or.inl h1⟩ hR0
      · exact absurd ⟨x, Or.inr h2⟩ hR0
      · exact h3
    have hB : BridgelessOn Q := by
      intro f hf B
      by_cases hfc : Core Q f
      · exact hcut f hfc B
      · obtain ⟨x, _, hx1⟩ := deg1_of_pendant (Classical.byContradiction fun hp => hfc ⟨hf, hp⟩)
        exact hR0 ⟨x, Or.inl hx1⟩
    apply hmin.1
    by_cases hiso : IsoTo k33 Q
    · exact k33_colourable hiso
    · exact hI G Q ⟨hloop, hconn, hB, hK⟩ (by have := vcount_le_n Q; omega)

/-- **bounded form of "(I) and (II) imply DMS"** -/
theorem dms_le (N : Nat) (hI : CubicLE N) (hII : IIcLE N) :
    ∀ (G : MGraph), Subcubic G → Loopless G → 2 * G.n ≤ N → ∀ P : Fin G.m → Prop, Colourable P 6 := by
  intro G hsub hloop hN P
  apply Classical.byContradiction
  intro hP
  obtain ⟨Q, -, hmin⟩ := exists_minimal 6 P hP
  exact minimal_impossible_le N hI hII hsub hloop hN hmin

end RH2F
