"""Write LeanProject/LeanProject/WitnessData.lean: zipper literals of a machine after n1 and n2
steps (hint data for `decide +kernel`; wrong data can only make the Lean checks fail).

Usage: python gen_witness_data.py <machine-string> <n1> <n2> <out.lean>
"""
import sys

from zipper_lit import parse


def lean_list(xs, indent="    ", per_line=14):
    words = ["true" if x else "false" for x in xs]
    if not words:
        return "[]"
    lines = []
    for i in range(0, len(words), per_line):
        lines.append(indent + ", ".join(words[i:i + per_line]))
    return "[\n" + ",\n".join(lines) + "]"


def zipper_after(tab, n):
    l, a, r, s = [], 0, [], "A"
    for _ in range(n):
        if s == "H":
            break
        w, d, nx = tab[(s, a)]
        if d == "R":
            l.insert(0, w)
            a = r.pop(0) if r else 0
        else:
            r.insert(0, w)
            a = l.pop(0) if l else 0
        s = nx
    return l, a, r, s


def main():
    ms, n1, n2, out = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
    tab = parse(ms)
    parts = [
        "import LeanProject.Zipper",
        "",
        "/-!",
        "# Hint data for the kernel check",
        "",
        "Zippers of `%s` after %d and %d steps, generated by" % (ms, n1, n2),
        "`search/gen_witness_data.py`. They are only compared against the kernel's own evaluation",
        "of `runZ`/`stepZ` (in `Witness249881.lean`); wrong data would make those checks fail and",
        "could not produce a false theorem.",
        "-/",
        "",
        "namespace BB6.Witness",
        "",
        "open BB6",
        "",
    ]
    for name, n in (("zA", n1), ("zB", n2)):
        l, a, r, s = zipper_after(tab, n)
        parts.append("/-- The zipper after %d steps: |l| = %d, |r| = %d, state %s. -/" % (n, len(l), len(r), s))
        parts.append("def %s : Z where" % name)
        parts.append("  l := " + lean_list(l))
        parts.append("  a := " + ("true" if a else "false"))
        parts.append("  r := " + lean_list(r))
        parts.append("  s := .%s" % s)
        parts.append("")
    parts.append("end BB6.Witness")
    parts.append("")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))
    print("wrote", out)


if __name__ == "__main__":
    main()
