#!/usr/bin/env python3
"""Generate a Makefile compiling LeanProject modules with plain `lean -o` (no lake)."""
import os, re
d = "LeanProject"
out = ["# generated by genmk.py", ".SECONDARY:", ""]
mods = sorted(f[:-5] for f in os.listdir(d) if f.endswith(".lean"))
for m in mods:
    src = open(os.path.join(d, m + ".lean"), encoding="utf8").read()
    deps = re.findall(r"^import LeanProject\.(\S+)", src, re.M)
    out.append("build/LeanProject/%s.olean: LeanProject/%s.lean %s" % (
        m, m, " ".join("build/LeanProject/%s.olean" % x for x in deps)))
    out.append("\t@./one.sh %s" % m)
    out.append("%s: build/LeanProject/%s.olean" % (m, m))
    out.append("")
out.append("root: " + " ".join("build/LeanProject/%s.olean" % m for m in mods))
open("Makefile", "w").write("\n".join(out) + "\n")
print(len(mods), "modules")
