"""Generate the Lean certificate files for a weighted two-colour blow-up solution.

    python3 gen.py SOLUTION.json PROJECT_DIR [--n N] [--chunk C] [--lib NAME]

Writes PROJECT_DIR/<lib>/Data/*.lean, <lib>/Chunk/*.lean, <lib>/Glue{R,B}.lean, <lib>/Main.lean
and PROJECT_DIR/<lib>/layers.txt (build order).  Defs.lean / Fast.lean are static and are copied
next to them by the caller (namespace RamseyCert, module prefix = lib name).

--n N restricts to the induced sub-template on the first N blocks (for scaling tests).
The solution file is the hill schema `weighted-two-color-blowup-v1`; bit j of row mask i is
red_rows[i][j].
"""
import argparse
import json
from fractions import Fraction
from pathlib import Path

import numpy as np

B = 32
MD = 2**B - 1
EPF = 64  # entries per data file

ap = argparse.ArgumentParser()
ap.add_argument("sol")
ap.add_argument("out")
ap.add_argument("--n", type=int, default=0)
ap.add_argument("--chunk", type=int, default=1)
ap.add_argument("--lib", default="RamseyCert")
ap.add_argument("--glue-only", action="store_true", help="rewrite only SymChk/Glue/Main/Final/layers (keep Data and Chunk files untouched)")
args = ap.parse_args()

d = json.load(open(args.sol))
assert d["schema"] == "weighted-two-color-blowup-v1"
n = args.n or len(d["weights"])
w = [int(x) for x in d["weights"][:n]]
rows = [r[:n] for r in d["red_rows"][:n]]
assert all(rows[i][j] == rows[j][i] for i in range(n) for j in range(n))
Q = sum(w)
assert Q < MD and all(1 <= x < 2**B for x in w)
LIB = args.lib
root = Path(args.out) / LIB
(root / "Data").mkdir(parents=True, exist_ok=True)
(root / "Chunk").mkdir(parents=True, exist_ok=True)
CH = args.chunk
nchunks = (n + CH - 1) // CH
nef = (n + EPF - 1) // EPF
FULLROW = 2**n - 1
Wpacked = sum(w[j] << (B * j) for j in range(n))
A = np.array([[int(c) for c in r] for r in rows], dtype=np.float64)
wv = np.array(w, dtype=np.float64)


def colour(name, col):
    C = A if col == "1" else 1.0 - A
    r = [sum(1 << j for j in range(n) if rows[i][j] == col) for i in range(n)]
    M = [sum(MD << (B * j) for j in range(n) if rows[i][j] == col) for i in range(n)]
    E = [sum(w[j] << (B * j) for j in range(n) if rows[i][j] == col) for i in range(n)]
    nb = [[j for j in range(n) if rows[i][j] == col] for i in range(n)]
    vals = []
    for a in range(n):
        idx = np.array(nb[a], dtype=np.int64)
        if len(idx) == 0:
            vals.append(0)
            continue
        S = C[np.ix_(idx, idx)]
        ww = wv[idx]
        X = (S * ww) @ S
        assert X.max(initial=0) < 2**53
        Y = (S * X) @ ww
        assert Y.max(initial=0) < 2**53
        vals.append(w[a] * sum(int(wb) * int(round(y)) for wb, y in zip(ww, Y)))
    return dict(name=name, r=r, M=M, E=E, nb=nb, vals=vals)


cols = [colour("R", "1"), colour("B", "0")]
NUM = sum(sum(c["vals"]) for c in cols)
P = Fraction(NUM, Q**4)
print("n", n, "Q", Q, "numer", NUM, "density", P, "ppt_ceil", -((-10**12 * P.numerator) // P.denominator))
REF = Fraction(10486266368, 768**4)
print("below reference:", P < REF)

hdr = "set_option maxRecDepth 1000000\nnamespace RamseyCert\n\n"
ftr = "\nend RamseyCert\n"


def write(rel, text):
    if args.glue_only and (rel.startswith("Data/") or rel.startswith("Chunk/")):
        return
    (root / rel).write_text(text, encoding="utf-8")


def lst(items, per=16):
    out = []
    for k in range(0, len(items), per):
        out.append("  " + ", ".join(items[k:k + per]))
    return "[\n" + ",\n".join(out) + "]"


# ---------------- Data/Base
t = f"import {LIB}.Defs\n\n/-! Generated by tools/gen.py from the solution file: packed weights, weights, row masks. -/\n\n" + hdr
t += f"/-- Number of blocks. -/\nabbrev N : ℕ := {n}\n\n"
t += f"/-- Weights packed in 32-bit fields. -/\ndef W : ℕ := {hex(Wpacked)}\n\n"
t += f"/-- The weights of the solution file. -/\ndef wl : List ℕ := {lst([str(x) for x in w])}\n\n"
for c in cols:
    X = c["name"]
    for i in range(n):
        t += f"def r{X}_{i} : ℕ := {hex(c['r'][i])}\n"
    t += f"\n/-- Row masks of colour {X}: bit j of entry i is set iff the pair (i,j) has the colour. -/\n"
    t += f"def rows{X} : List ℕ := {lst([f'r{X}_{i}' for i in range(n)])}\n\n"
write("Data/Base.lean", t + ftr)

# ---------------- Data/Ent
ent_mods = []
SEG = 128
nseg = (n + SEG - 1) // SEG
layers = [[f"{LIB}.Defs"], [f"{LIB}.Fast", f"{LIB}.Data.Base", f"{LIB}.SymDefs"], [f"{LIB}.Sym"] + [f"{LIB}.SymChk{k}" for k in range(nseg)], [f"{LIB}.Data.Ents"], [], [], [f"{LIB}.GlueR", f"{LIB}.GlueB"], [f"{LIB}.Main"], [f"{LIB}.Limit"], [f"{LIB}.Mono"], [f"{LIB}.Final"]]
for c in cols:
    X = c["name"]
    for k in range(nef):
        t = f"import {LIB}.Data.Base\n\n" + hdr
        for i in range(k * EPF, min(n, (k + 1) * EPF)):
            t += f"def e{X}_{i} : Ent := ⟨{i}, {w[i]}, r{X}_{i}, {hex(c['M'][i])}, {hex(c['E'][i])}⟩\n"
        write(f"Data/Ent{X}{k}.lean", t + ftr)
        layers[2].append(f"{LIB}.Data.Ent{X}{k}")
        ent_mods.append(f"{LIB}.Data.Ent{X}{k}")
t = "".join(f"import {m}\n" for m in ent_mods) + "\n" + hdr
for c in cols:
    X = c["name"]
    t += f"def ents{X} : List Ent := {lst([f'e{X}_{i}' for i in range(n)])}\n\n"
write("Data/Ents.lean", t + ftr)

# ---------------- Chunk
for c in cols:
    X = c["name"]
    for k in range(nchunks):
        t = f"import {LIB}.Data.Ents\n\n" + hdr
        for a in range(k * CH, min(n, (k + 1) * CH)):
            t += f"def nb{X}_{a} : List Ent := {lst([f'e{X}_{j}' for j in c['nb'][a]])}\n"
            t += f"theorem nbOK{X}_{a} : nb{X}_{a} = nbhd ents{X} e{X}_{a} := by decide +kernel\n"
            t += f"theorem mkOK{X}_{a} : mkEnt {B} {n} W r{X}_{a} {a} = e{X}_{a} := by decide +kernel\n"
            t += f"theorem t{X}_{a} : kTermA {MD} e{X}_{a} nb{X}_{a} = {c['vals'][a]} := by decide +kernel\n\n"
        write(f"Chunk/{X}{k}.lean", t + ftr)
        layers[4 if X == "R" else 5].append(f"{LIB}.Chunk.{X}{k}")

# ---------------- Glue
for c in cols:
    X = c["name"]
    t = "".join(f"import {LIB}.Chunk.{X}{k}\n" for k in range(nchunks)) + f"import {LIB}.Fast\n\n" + hdr
    t += f"/-- Contribution of a block of colour {X}. -/\nnoncomputable def g{X} (ea : Ent) : ℕ := kTermA {MD} ea (nbhd ents{X} ea)\n\n"
    for a in range(n):
        t += (f"theorem g{X}_{a} : g{X} e{X}_{a} = {c['vals'][a]} :=\n"
              f"  (congrArg (kTermA {MD} e{X}_{a}) nbOK{X}_{a}).symm.trans t{X}_{a}\n")
    t += f"\ndef vals{X} : List ℕ := {lst([str(v) for v in c['vals']], 4)}\n\n"
    t += f"theorem map{X} : ents{X}.map g{X} = vals{X} := by\n  simp only [ents{X}, vals{X}, List.map_cons, List.map_nil,\n    "
    t += ", ".join(f"g{X}_{a}" for a in range(n)) + "]\n\n"
    t += f"theorem sum{X} : (ents{X}.map g{X}).sum = {sum(c['vals'])} := by\n  rw [map{X}]; decide +kernel\n\n"
    t += f"theorem mkList{X} : mkAll {B} {n} W rows{X} = {lst([f'mkEnt {B} {n} W r{X}_{i} {i}' for i in range(n)], 4)} := by\n  rfl\n\n"
    t += f"theorem mkAll{X} : ents{X} = mkAll {B} {n} W rows{X} := by\n  rw [mkList{X}]\n  simp only [ents{X},\n    "
    t += ", ".join(f"mkOK{X}_{a}" for a in range(n)) + "]\n\n"
    t += f"theorem hsum{X} : ((List.range {n}).map (wOf W {B})).sum < 2 ^ {B} - 1 := by decide +kernel\n\n"
    t += (f"theorem K4{X} : K4 {n} (wOf W {B}) (adjOf rows{X}) = {sum(c['vals'])} := by\n"
          f"  have h := colour_total {B} {n} W {MD} rows{X} ents{X} (by norm_num) (by decide +kernel) mkAll{X} hsum{X}\n"
          f"  exact h.symm.trans sum{X}\n")
    write(f"Glue{X}.lean", t + ftr)

# ---------------- SymChk
for k in range(nseg):
    ln = min(SEG, n - k * SEG)
    write(f"SymChk{k}.lean", f"import {LIB}.Data.Base\nimport {LIB}.SymDefs\n\n" + hdr +
          f"theorem symchk_{k} : symRows rowsR ((rowsR.drop {k * SEG}).take {ln}) {k * SEG} = true := by decide +kernel\n" + ftr)

# ---------------- Main
SYM = f"theorem adjR_symm (i j : ℕ) (hi : i < {n}) (hj : j < {n}) : adjOf rowsR i j = adjOf rowsR j i := by\n  have hl : rowsR.length = {n} := rowsR_len\n"
for k in range(nseg):
    ln = min(SEG, n - k * SEG)
    call = f"exact adjOf_symm_of_check rowsR {k * SEG} {ln} symchk_{k} i j (by omega) (by omega) (by omega) (by omega)\n"
    if k < nseg - 1:
        SYM += f"  rcases Nat.lt_or_ge i {(k + 1) * SEG} with h{k} | h{k}\n  · " + call
    else:
        SYM += "  " + call
SYM += "\n/-- The colour matrix of the solution is symmetric. -/\ntheorem sol_symm : sol.Symmetric := fun a b => adjR_symm a b a.isLt b.isLt\n\n#print axioms sol_symm\n"
PPT = -((-10**12 * P.numerator) // P.denominator)
SYM += f"""
/-- The hill metric `density_ppt` = ⌈10^12 · density⌉. -/
theorem sol_ppt : ⌈(10 ^ 12 : ℚ) * sol.density⌉ = {PPT} := by
  rw [sol_density, Int.ceil_eq_iff]
  constructor <;> norm_num

#print axioms sol_ppt
"""
RSUM, BSUM = sum(cols[0]["vals"]), sum(cols[1]["vals"])
LT = """/-- The density is below the reference value `10486266368 / 768^4` (arXiv:2206.04036v3). -/
theorem sol_lt_ref : sol.density < 10486266368 / 768 ^ 4 := by
  rw [sol_density]
  norm_num

#print axioms sol_lt_ref
""" if P < REF else ""
t = f"import {LIB}.GlueR\nimport {LIB}.GlueB\nimport {LIB}.Sym\n" + "".join(f"import {LIB}.SymChk{k}\n" for k in range(nseg)) + "\n"
t += "/-!\n# The certificate\n\n`sol` is the solution file as a `Template`; `sol_density` and `sol_lt_ref` are the results.\n-/\n\n" + hdr
t += f"""/-- The solution: weights `wl`, red pairs given by the row masks `rowsR`. -/
def sol : Template := ⟨{n}, fun i => wl.getD i 0, fun i j => adjOf rowsR i j⟩

theorem wl_ok : wl = (List.range {n}).map (wOf W {B}) := by decide +kernel

theorem rowsB_ok : rowsB = rowsR.map (fun r => Nat.xor r (2 ^ {n} - 1)) := by decide +kernel

theorem rowsR_len : rowsR.length = {n} := by decide +kernel

theorem sol_w (i : Fin sol.n) : sol.w i = wOf W {B} i := by
  show wl.getD i 0 = wOf W {B} i
  rw [wl_ok]; exact getD_map_range _ _ _ i.isLt

theorem sol_red (i j : Fin sol.n) : sol.red i j = adjOf rowsR i j := rfl

theorem sol_split : sol.numer = K4 {n} (wOf W {B}) (adjOf rowsR)
    + K4 {n} (wOf W {B}) (fun a b => !adjOf rowsR a b) :=
  Template.numer_eq sol {n} rfl (wOf W {B}) (adjOf rowsR) sol_w sol_red

theorem K4Bneg : K4 {n} (wOf W {B}) (fun a b => !adjOf rowsR a b) = {BSUM} :=
  (K4_blue {n} (wOf W {B}) rowsR rowsB rowsR_len rowsB_ok).trans K4B

theorem sol_numer_sum : sol.numer = {RSUM} + {BSUM} :=
  sol_split.trans (congrArg₂ HAdd.hAdd K4R K4Bneg)

/-- Monochromatic-K4 numerator of the solution. -/
theorem sol_numer : sol.numer = {NUM} := sol_numer_sum.trans (by norm_num)

theorem sol_total_list : sol.total = ((List.range {n}).map (wOf W {B})).sum :=
  Template.total_eq sol {n} rfl (wOf W {B}) sol_w

theorem wl_sum : ((List.range {n}).map (wOf W {B})).sum = {Q} := by decide +kernel

/-- Total weight of the solution. -/
theorem sol_total : sol.total = {Q} := sol_total_list.trans wl_sum

/-- Exact density of the solution. -/
theorem sol_density : sol.density = {P.numerator} / {P.denominator} := by
  unfold Template.density
  rw [sol_numer, sol_total]
  norm_num

#print axioms sol_density
{LT}
{SYM}"""
write("Main.lean", t + ftr)
# ---------------- Final (needs Limit.lean) and Native (optional cross-check, NOT standard axioms)
t = f"import {LIB}.Main\nimport {LIB}.Limit\nimport {LIB}.Mono\n\n"
t += "/-!\n# Consequence for the K4 Ramsey multiplicity constant\n\n`ramseyMultK4` (see `Limit.lean`) is the liminf of the minimum density of monochromatic K4 over all\n2-colourings of the complete graph on m vertices.\n-/\n\n" + hdr
t += f"""/-- The K4 Ramsey multiplicity constant is at most the density of the solution. -/
theorem ramseyMultK4_le_sol :
    ramseyMultK4 ≤ {P.numerator} / {P.denominator} := by
  have h := ramseyMultK4_le_density sol sol_symm (by rw [sol_total]; norm_num)
  rw [sol_density] at h
  exact h.trans (le_of_eq (by norm_num))

#print axioms ramseyMultK4_le_sol
"""
if P < REF:
    t += """
/-- ... hence strictly below the reference value `10486266368 / 768^4`. -/
theorem ramseyMultK4_lt_ref : ramseyMultK4 < 10486266368 / 768 ^ 4 :=
  lt_of_le_of_lt ramseyMultK4_le_sol (by norm_num)

#print axioms ramseyMultK4_lt_ref
"""
t += f"""
/-- Finite form: for every `m ≥ 4` the minimum number of monochromatic K4 over all 2-colourings of the
complete graph on `m` vertices is at most `P * C(m,4)` (uses the monotonicity proved in `Mono.lean`). -/
theorem minMonoK4_density_le_sol (m : ℕ) (hm : 4 ≤ m) :
    (minMonoK4 m : ℝ) / (m.choose 4 : ℝ) ≤ {P.numerator} / {P.denominator} :=
  (minMonoK4_density_le m hm).trans ramseyMultK4_le_sol

#print axioms minMonoK4_density_le_sol
"""
if P < REF:
    t += """
/-- The limit defining the K4 Ramsey multiplicity constant exists and is below the reference value. -/
theorem ramseyMultK4_limit_lt_ref :
    ∃ L : ℝ, Filter.Tendsto (fun m : ℕ => (minMonoK4 m : ℝ) / (m.choose 4 : ℝ)) Filter.atTop (nhds L) ∧
      L < 10486266368 / 768 ^ 4 :=
  ⟨ramseyMultK4, ramseyMultK4_tendsto, ramseyMultK4_lt_ref⟩

#print axioms ramseyMultK4_limit_lt_ref
"""
write("Final.lean", t + ftr)
t = f"import {LIB}.Fast\nimport {LIB}.Data.Base\n\n"
t += "/-!\n# Cross-check with compiled evaluation (`native_decide`) - NOT part of the kernel certificate\n\nThe computable evaluator `fastK` (proved equal to the specification in `fastK_eq`) is run on the\nrow masks directly (it rebuilds all packed data itself). These theorems depend on the extra axiom\nintroduced by `native_decide` (trust in the Lean compiler/interpreter and GMP).\n-/\n\n" + hdr
t += f"theorem native_fastK_R : fastK {B} {n} W rowsR = {RSUM} := by native_decide\n\n"
t += f"theorem native_fastK_B : fastK {B} {n} W rowsB = {BSUM} := by native_decide\n\n"
t += "#print axioms native_fastK_R\n#print axioms native_fastK_B\n"
write("Native.lean", t + ftr)
(Path(args.out) / f"{LIB}.lean").write_text(f"import {LIB}.Main\n", encoding="utf-8")
write("layers.txt", "\n".join(" ".join(l) for l in layers) + "\n")
write("values.json", json.dumps({"n": n, "Q": Q, "numer": NUM, "density": [P.numerator, P.denominator],
                                 "below_ref": P < REF, "solution": str(args.sol)}))
print("written", root)
