/-
  GPFive.lean — generalized Petersen graphs: GP(n,2) (n ≥ 5) and GP(n,3) (n ≥ 7) have star edge colourings
  with 5 colours.

  GP(n,k): vertices u_i, v_i (i ∈ Z/n); edges u_i u_{i+1} (outer), u_i v_i (spokes), v_i v_{i+k} (inner).
  Encoding as cyclic block graphs (`BlockStar.BG`): u_i = 2i, v_i = 2i+1 in `Fin (n * 2)`; edge (i, s) has number
  3i+s in `Fin (n * 3)`, s = 0: u_i u_{i+1}, s = 1: u_i v_i, s = 2: v_i v_{i+k}.  GP(n,2) is `GPetersen2.gp2 n`.
  The colourings are those of the star6 facts 2f8113cb26f31818 (k = 2) and cab2712392b5deec (k = 3): a periodic
  part (period 5 resp. 4) followed by a seam whose length depends on n mod 5 resp. n mod 4, and explicit
  colourings for the small n.  (Generated by gen_gp.py from the pattern tables of the two facts.)
-/
import GPetersen2Defs

namespace GP2Five
open BlockStar GPetersen2

/-- colour (0..4) of the edge type `s` in a block with pattern `c = [outer, spoke, inner]` -/
def ct (c : List Nat) (s : Nat) : Nat := (c.getD s 0) % 5

theorem ct_lt : ∀ c s, ct c s < 5 := fun _ _ => Nat.mod_lt _ (by decide)

/-- row r (r = n mod 5): the periodic patterns P0..P4 followed by the seam S{r}_0 .. S{r}_{r+4}
    (fact 2f8113cb26f31818, colours shifted to 0..4) -/
def tabs : List (List (List Nat)) :=
  [[[0, 1, 0], [3, 2, 4], [1, 4, 3], [2, 3, 2], [4, 0, 1], [0, 1, 0], [3, 2, 4], [1, 4, 3], [3, 0, 2], [4, 2, 1]],
   [[0, 1, 0], [3, 2, 4], [1, 4, 3], [2, 3, 2], [4, 0, 1], [3, 0, 1], [0, 2, 4], [1, 4, 0], [0, 2, 0], [4, 3, 2], [2, 3, 1]],
   [[0, 1, 0], [3, 2, 4], [1, 4, 3], [2, 3, 2], [4, 0, 1], [3, 0, 1], [0, 2, 4], [1, 4, 3], [2, 3, 0], [1, 4, 0], [4, 3, 2], [2, 3, 1]],
   [[0, 1, 0], [3, 2, 4], [1, 4, 3], [2, 3, 2], [4, 0, 1], [3, 0, 1], [0, 4, 2], [4, 2, 0], [1, 3, 0], [2, 3, 4], [1, 3, 4], [0, 3, 2], [4, 2, 1]],
   [[0, 1, 0], [3, 2, 4], [1, 4, 3], [2, 3, 2], [4, 0, 1], [0, 1, 0], [3, 2, 4], [1, 4, 2], [0, 2, 3], [1, 3, 4], [2, 4, 0], [0, 3, 0], [4, 1, 2], [3, 2, 1]]]

/-- explicit colourings for n = 5..9 (row n - 5) -/
def smallTab : List (List (List Nat)) :=
  [[[0, 1, 2], [1, 2, 4], [3, 4, 0], [2, 0, 3], [3, 4, 1]],
   [[0, 1, 2], [1, 2, 4], [3, 4, 0], [0, 2, 0], [4, 1, 3], [2, 3, 1]],
   [[0, 1, 2], [1, 2, 4], [3, 4, 0], [4, 0, 2], [1, 2, 3], [3, 0, 3], [2, 4, 1]],
   [[0, 1, 2], [1, 2, 3], [3, 4, 0], [1, 0, 2], [4, 2, 1], [2, 1, 0], [3, 0, 3], [2, 4, 1]],
   [[0, 1, 2], [1, 2, 1], [3, 4, 0], [2, 4, 0], [3, 4, 1], [4, 1, 2], [1, 2, 0], [3, 0, 3], [2, 4, 3]]]

/-- index into row `n % 5` of `tabs` of the pattern of block `J`: the periodic part has length
    `n - n % 5 - 5`, then comes the seam of length `n % 5 + 5` -/
def idx (n J : Nat) : Nat :=
  if J < n - n % 5 - 5 then J % 5 else 5 + (J - (n - n % 5 - 5))

/-- the pattern of block `J` -/
def chi (n J : Nat) : List Nat :=
  if n < 10 then (smallTab.getD (n - 5) []).getD J [] else (tabs.getD (n % 5) []).getD (idx n J) []

/-- the colouring -/
def col (n : Nat) : Fin (gp2 n).m → Fin 5 := bcol 3 ct ct_lt (chi n)

abbrev winsAll (n : Nat) : Prop :=
  ∀ j, j < n → winOK gpWir ct (fun _ => ()) (fun p => chi n ((j + p) % n)) = true

theorem Wsmall : ∀ n, n < 25 → 5 ≤ n → winsAll n := by decide +kernel

theorem rep {n : Nat} (hn : 25 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 20 + n % 5 ∧ ∀ p, p ≤ 6 →
      idx (20 + n % 5) ((j' + p) % (20 + n % 5)) = idx n ((j + p) % n) := by
  have hm : (20 + n % 5) % 5 = n % 5 := by omega
  rcases (show j + 6 < n - n % 5 - 5 ∨ n - n % 5 - 5 ≤ j + 6 by omega) with c | c
  · refine ⟨j % 5, by omega, ?_⟩
    intro p hp
    rw [SeamSeq.modc hj (by omega), SeamSeq.modc (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (20 + n % 5) - n, by omega, ?_⟩
    intro p hp
    rw [SeamSeq.modc hj (by omega), SeamSeq.modc (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,2).** For every `n ≥ 5`, `col n` is a star edge colouring of GP(n,2) with 5 colours. -/
theorem star5 (n : Nat) (hn : 5 ≤ n) : (gp2 n).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 25
  · exact ⟨_, _, fun p _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 20 + n % 5 < 25 := by omega
    refine ⟨fun _ => (), fun p => chi (20 + n % 5) ((j' + p) % (20 + n % 5)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro p hp
    have hp' : p ≤ 6 := hp
    refine ⟨rfl, ?_⟩
    have e := hrep p hp'
    have h1 : ¬ n < 10 := by omega
    have h2 : ¬ 20 + n % 5 < 10 := by omega
    have hm : (20 + n % 5) % 5 = n % 5 := by omega
    show chi (20 + n % 5) ((j' + p) % (20 + n % 5)) = chi n ((j + p) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

end GP2Five

#print axioms GP2Five.star5

namespace GP3Five
open BlockStar GPetersen2

def qjmp (s : Nat) : Nat := match s with
  | 0 => 1 | 1 => 0 | _ => 3

/-- wiring of GP(n,3): edge types 0: u_i u_{i+1}, 1: u_i v_i, 2: v_i v_{i+3}; vertex types u = 0, v = 1 -/
def gp3Wir : Wir Unit 2 3 where
  D := 3
  src := fun _ s => psrc s
  jmp := fun _ s => qjmp s
  dst := fun _ s => pdst s
  hsrc := by intro w s; unfold psrc; split <;> omega
  hdst := by intro w s; unfold pdst; split <;> omega
  hjmp := by intro w s; unfold qjmp; split <;> omega
  jumps := [0, 1, 3]
  hjmps := by intro w s; unfold qjmp; split <;> decide

/-- the generalized Petersen graph GP(n,3): u_i = 2i, v_i = 2i+1; edges 3i: u_i u_{i+1}, 3i+1: u_i v_i, 3i+2: v_i v_{i+3} -/
def gp3 (n : Nat) : MGraph := BG gp3Wir n (fun _ => ())

/-- colour (0..4) of the edge type `s` in a block with pattern `c = [outer, spoke, inner]` -/
def ct (c : List Nat) (s : Nat) : Nat := (c.getD s 0) % 5

theorem ct_lt : ∀ c s, ct c s < 5 := fun _ _ => Nat.mod_lt _ (by decide)

/-- row r (r = n mod 4): the periodic patterns P0..P3 followed by the seam S{r}_0 .. S{r}_{r+3}
    (fact cab2712392b5deec, colours shifted to 0..4) -/
def tabs : List (List (List Nat)) :=
  [[[0, 1, 2], [2, 4, 0], [4, 1, 3], [3, 1, 0], [4, 1, 2], [2, 0, 4], [4, 1, 3], [3, 1, 0]],
   [[0, 1, 2], [2, 4, 0], [4, 1, 3], [3, 1, 0], [0, 2, 1], [3, 4, 1], [2, 1, 4], [4, 0, 3], [3, 2, 0]],
   [[0, 1, 2], [2, 4, 0], [4, 1, 3], [3, 1, 0], [0, 1, 2], [2, 4, 2], [3, 1, 4], [0, 1, 4], [4, 1, 3], [3, 2, 0]],
   [[0, 1, 2], [2, 4, 0], [4, 1, 3], [3, 1, 0], [4, 1, 2], [2, 1, 0], [4, 1, 4], [0, 3, 1], [1, 2, 4], [0, 2, 3], [3, 4, 0]]]

/-- explicit colourings for n = 7..13 (row n - 7) -/
def smallTab : List (List (List Nat)) :=
  [[[0, 1, 2], [1, 2, 4], [3, 4, 1], [1, 4, 0], [2, 0, 3], [4, 0, 3], [2, 3, 2]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 0], [3, 0, 3], [4, 1, 2], [2, 1, 3], [3, 1, 4], [2, 4, 1]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 0], [3, 0, 4], [4, 1, 0], [1, 3, 2], [2, 0, 3], [3, 1, 4], [2, 4, 1]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 0, 3], [4, 1, 0], [0, 2, 1], [2, 4, 1], [4, 1, 3], [3, 0, 4], [2, 4, 0]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 1], [4, 0, 3], [3, 0, 1], [2, 4, 0], [0, 4, 1], [4, 3, 0], [2, 1, 3], [3, 0, 4], [2, 4, 2]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 0], [3, 0, 3], [4, 1, 0], [2, 3, 1], [0, 1, 4], [2, 4, 1], [4, 3, 2], [1, 0, 3], [3, 2, 4], [2, 4, 1]],
   [[0, 1, 2], [1, 2, 3], [2, 3, 0], [3, 0, 3], [4, 1, 2], [2, 3, 2], [0, 1, 4], [3, 4, 0], [2, 1, 0], [0, 3, 0], [2, 1, 3], [3, 1, 4], [2, 4, 1]]]

/-- index into row `n % 4` of `tabs` of the pattern of block `J`: the periodic part has length
    `n - n % 4 - 4`, then comes the seam of length `n % 4 + 4` -/
def idx (n J : Nat) : Nat :=
  if J < n - n % 4 - 4 then J % 4 else 4 + (J - (n - n % 4 - 4))

/-- the pattern of block `J` -/
def chi (n J : Nat) : List Nat :=
  if n < 14 then (smallTab.getD (n - 7) []).getD J [] else (tabs.getD (n % 4) []).getD (idx n J) []

/-- the colouring -/
def col (n : Nat) : Fin (gp3 n).m → Fin 5 := bcol 3 ct ct_lt (chi n)

abbrev winsAll (n : Nat) : Prop :=
  ∀ j, j < n → winOK gp3Wir ct (fun _ => ()) (fun p => chi n ((j + p) % n)) = true

theorem Wsmall : ∀ n, n < 24 → 7 ≤ n → winsAll n := by decide +kernel

theorem rep {n : Nat} (hn : 24 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 20 + n % 4 ∧ ∀ p, p ≤ 9 →
      idx (20 + n % 4) ((j' + p) % (20 + n % 4)) = idx n ((j + p) % n) := by
  have hm : (20 + n % 4) % 4 = n % 4 := by omega
  rcases (show j + 9 < n - n % 4 - 4 ∨ n - n % 4 - 4 ≤ j + 9 by omega) with c | c
  · refine ⟨j % 4, by omega, ?_⟩
    intro p hp
    rw [SeamSeq.modc hj (by omega), SeamSeq.modc (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (20 + n % 4) - n, by omega, ?_⟩
    intro p hp
    rw [SeamSeq.modc hj (by omega), SeamSeq.modc (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,3).** For every `n ≥ 7`, `col n` is a star edge colouring of GP(n,3) with 5 colours. -/
theorem star5 (n : Nat) (hn : 7 ≤ n) : (gp3 n).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 24
  · exact ⟨_, _, fun p _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 20 + n % 4 < 24 := by omega
    refine ⟨fun _ => (), fun p => chi (20 + n % 4) ((j' + p) % (20 + n % 4)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro p hp
    have hp' : p ≤ 9 := hp
    refine ⟨rfl, ?_⟩
    have e := hrep p hp'
    have h1 : ¬ n < 14 := by omega
    have h2 : ¬ 20 + n % 4 < 14 := by omega
    have hm : (20 + n % 4) % 4 = n % 4 := by omega
    show chi (20 + n % 4) ((j' + p) % (20 + n % 4)) = chi n ((j + p) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

end GP3Five

#print axioms GP3Five.star5
