/- GPn12W6.lean — window checks for GP(n,12), 63 ≤ n < 68 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc6 : ∀ n, n < 68 → 63 ≤ n → winsAll n := by decide +kernel

end GPn12
