/-
  GPn11.lean — generalized Petersen graphs GP(n,11), n ≥ 23: star edge colourings with 5 colours
  (colouring in GPn11T.lean, window checks for n < 72 in GPn11W1..8.lean; generated by search/gen_gpk.py).
-/
import GPn11W1
import GPn11W2
import GPn11W3
import GPn11W4
import GPn11W5
import GPn11W6
import GPn11W7
import GPn11W8

namespace GPn11
open BlockStar GPk

theorem Wsmall : ∀ n, n < 72 → 23 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 34
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 42
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 49
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 55
  · exact Wc4 n c4 (by omega)
  by_cases c5 : n < 61
  · exact Wc5 n c5 (by omega)
  by_cases c6 : n < 66
  · exact Wc6 n c6 (by omega)
  by_cases c7 : n < 71
  · exact Wc7 n c7 (by omega)
  exact Wc8 n h1 (by omega)

theorem rep {n : Nat} (hn : 72 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 64 + n % 8 ∧ ∀ q, q ≤ 33 →
      idx (64 + n % 8) ((j' + q) % (64 + n % 8)) = idx n ((j + q) % n) := by
  have hm : (64 + n % 8) % 8 = n % 8 := by omega
  rcases (show j + 33 < n - n % 8 - 16 ∨ n - n % 8 - 16 ≤ j + 33 by omega) with c | c
  · refine ⟨j % 8, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (64 + n % 8) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,11).** For every `n ≥ 23`, `col n` is a star edge colouring of GP(n,11) with 5 colours. -/
theorem star5 (n : Nat) (hn : 23 ≤ n) : (gp n 11).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 72
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 64 + n % 8 < 72 := by omega
    refine ⟨fun _ => (), fun q => chi (64 + n % 8) ((j' + q) % (64 + n % 8)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 33 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 47 := by omega
    have h2 : ¬ 64 + n % 8 < 47 := by omega
    have hm : (64 + n % 8) % 8 = n % 8 := by omega
    show chi (64 + n % 8) ((j' + q) % (64 + n % 8)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 11).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,11), n ≥ 23: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 23 ≤ n) : StarFam (gp n 11) 5 :=
  ⟨subcubic n, gp_loopless n 11 (by decide) (by show max 1 11 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn11

#check @GPn11.star5
#check @GPn11.family
#print axioms GPn11.star5
#print axioms GPn11.family
