/- GPn11W2.lean — window checks for GP(n,11), 34 ≤ n < 42 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc2 : ∀ n, n < 42 → 34 ≤ n → winsAll n := by decide +kernel

end GPn11
