/- GPn10W2.lean — window checks for GP(n,10), 33 ≤ n < 42 (generated by search/gen_gpk.py) -/
import GPn10T

namespace GPn10

theorem Wc2 : ∀ n, n < 42 → 33 ≤ n → winsAll n := by decide +kernel

end GPn10
