/- GPn11W4.lean — window checks for GP(n,11), 49 ≤ n < 55 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc4 : ∀ n, n < 55 → 49 ≤ n → winsAll n := by decide +kernel

end GPn11
