/- GPn13W2.lean — window checks for GP(n,13), 37 ≤ n < 45 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc2 : ∀ n, n < 45 → 37 ≤ n → winsAll n := by decide +kernel

end GPn13
