/- GPn14W9.lean — window checks for GP(n,14), 79 ≤ n < 83 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc9 : ∀ n, n < 83 → 79 ≤ n → winsAll n := by decide +kernel

end GPn14
