/- GPn13W5.lean — window checks for GP(n,13), 58 ≤ n < 63 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc5 : ∀ n, n < 63 → 58 ≤ n → winsAll n := by decide +kernel

end GPn13
