/- GPn15W9.lean — window checks for GP(n,15), 79 ≤ n < 80 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc9 : ∀ n, n < 80 → 79 ≤ n → winsAll n := by decide +kernel

end GPn15
