/-
  GPn12.lean — generalized Petersen graphs GP(n,12), n ≥ 25: star edge colourings with 5 colours
  (colouring in GPn12T.lean, window checks for n < 72 in GPn12W1..7.lean; generated by search/gen_gpk.py).
-/
import GPn12W1
import GPn12W2
import GPn12W3
import GPn12W4
import GPn12W5
import GPn12W6
import GPn12W7

namespace GPn12
open BlockStar GPk

theorem Wsmall : ∀ n, n < 72 → 25 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 36
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 44
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 51
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 57
  · exact Wc4 n c4 (by omega)
  by_cases c5 : n < 63
  · exact Wc5 n c5 (by omega)
  by_cases c6 : n < 68
  · exact Wc6 n c6 (by omega)
  exact Wc7 n h1 (by omega)

theorem rep {n : Nat} (hn : 72 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 63 + n % 9 ∧ ∀ q, q ≤ 36 →
      idx (63 + n % 9) ((j' + q) % (63 + n % 9)) = idx n ((j + q) % n) := by
  have hm : (63 + n % 9) % 9 = n % 9 := by omega
  rcases (show j + 36 < n - n % 9 - 18 ∨ n - n % 9 - 18 ≤ j + 36 by omega) with c | c
  · refine ⟨j % 9, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (63 + n % 9) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,12).** For every `n ≥ 25`, `col n` is a star edge colouring of GP(n,12) with 5 colours. -/
theorem star5 (n : Nat) (hn : 25 ≤ n) : (gp n 12).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 72
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 63 + n % 9 < 72 := by omega
    refine ⟨fun _ => (), fun q => chi (63 + n % 9) ((j' + q) % (63 + n % 9)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 36 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 52 := by omega
    have h2 : ¬ 63 + n % 9 < 52 := by omega
    have hm : (63 + n % 9) % 9 = n % 9 := by omega
    show chi (63 + n % 9) ((j' + q) % (63 + n % 9)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 12).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,12), n ≥ 25: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 25 ≤ n) : StarFam (gp n 12) 5 :=
  ⟨subcubic n, gp_loopless n 12 (by decide) (by show max 1 12 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn12

#check @GPn12.star5
#check @GPn12.family
#print axioms GPn12.star5
#print axioms GPn12.family
