/- GPn10W3.lean — window checks for GP(n,10), 42 ≤ n < 49 (generated by search/gen_gpk.py) -/
import GPn10T

namespace GPn10

theorem Wc3 : ∀ n, n < 49 → 42 ≤ n → winsAll n := by decide +kernel

end GPn10
