/- GPn13W4.lean — window checks for GP(n,13), 52 ≤ n < 58 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc4 : ∀ n, n < 58 → 52 ≤ n → winsAll n := by decide +kernel

end GPn13
