/- GPn15W5.lean — window checks for GP(n,15), 60 ≤ n < 65 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc5 : ∀ n, n < 65 → 60 ≤ n → winsAll n := by decide +kernel

end GPn15
