/- GPn10W4.lean — window checks for GP(n,10), 49 ≤ n < 54 (generated by search/gen_gpk.py) -/
import GPn10T

namespace GPn10

theorem Wc4 : ∀ n, n < 54 → 49 ≤ n → winsAll n := by decide +kernel

end GPn10
