/- GPn13W3.lean — window checks for GP(n,13), 45 ≤ n < 52 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc3 : ∀ n, n < 52 → 45 ≤ n → winsAll n := by decide +kernel

end GPn13
