/- GPn14W10.lean — window checks for GP(n,14), 83 ≤ n < 87 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc10 : ∀ n, n < 87 → 83 ≤ n → winsAll n := by decide +kernel

end GPn14
