/- GPn14W6.lean — window checks for GP(n,14), 65 ≤ n < 70 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc6 : ∀ n, n < 70 → 65 ≤ n → winsAll n := by decide +kernel

end GPn14
