/- GPn15W3.lean — window checks for GP(n,15), 47 ≤ n < 54 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc3 : ∀ n, n < 54 → 47 ≤ n → winsAll n := by decide +kernel

end GPn15
