/- GPn11W5.lean — window checks for GP(n,11), 55 ≤ n < 61 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc5 : ∀ n, n < 61 → 55 ≤ n → winsAll n := by decide +kernel

end GPn11
