/- GPn11W3.lean — window checks for GP(n,11), 42 ≤ n < 49 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc3 : ∀ n, n < 49 → 42 ≤ n → winsAll n := by decide +kernel

end GPn11
