/- GPn15W6.lean — window checks for GP(n,15), 65 ≤ n < 70 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc6 : ∀ n, n < 70 → 65 ≤ n → winsAll n := by decide +kernel

end GPn15
