/-
  GPn10.lean — generalized Petersen graphs GP(n,10), n ≥ 21: star edge colourings with 5 colours
  (colouring in GPn10T.lean, window checks for n < 54 in GPn10W1..4.lean; generated by search/gen_gpk.py).
-/
import GPn10W1
import GPn10W2
import GPn10W3
import GPn10W4

namespace GPn10
open BlockStar GPk

theorem Wsmall : ∀ n, n < 54 → 21 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 33
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 42
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 49
  · exact Wc3 n c3 (by omega)
  exact Wc4 n h1 (by omega)

theorem rep {n : Nat} (hn : 54 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 48 + n % 6 ∧ ∀ q, q ≤ 30 →
      idx (48 + n % 6) ((j' + q) % (48 + n % 6)) = idx n ((j + q) % n) := by
  have hm : (48 + n % 6) % 6 = n % 6 := by omega
  rcases (show j + 30 < n - n % 6 - 12 ∨ n - n % 6 - 12 ≤ j + 30 by omega) with c | c
  · refine ⟨j % 6, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (48 + n % 6) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,10).** For every `n ≥ 21`, `col n` is a star edge colouring of GP(n,10) with 5 colours. -/
theorem star5 (n : Nat) (hn : 21 ≤ n) : (gp n 10).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 54
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 48 + n % 6 < 54 := by omega
    refine ⟨fun _ => (), fun q => chi (48 + n % 6) ((j' + q) % (48 + n % 6)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 30 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 39 := by omega
    have h2 : ¬ 48 + n % 6 < 39 := by omega
    have hm : (48 + n % 6) % 6 = n % 6 := by omega
    show chi (48 + n % 6) ((j' + q) % (48 + n % 6)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 10).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,10), n ≥ 21: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 21 ≤ n) : StarFam (gp n 10) 5 :=
  ⟨subcubic n, gp_loopless n 10 (by decide) (by show max 1 10 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn10

#check @GPn10.star5
#check @GPn10.family
#print axioms GPn10.star5
#print axioms GPn10.family
