/- GPn12W2.lean — window checks for GP(n,12), 36 ≤ n < 44 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc2 : ∀ n, n < 44 → 36 ≤ n → winsAll n := by decide +kernel

end GPn12
