/- GPn12W1.lean — window checks for GP(n,12), 25 ≤ n < 36 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc1 : ∀ n, n < 36 → 25 ≤ n → winsAll n := by decide +kernel

end GPn12
