/- GPn14W11.lean — window checks for GP(n,14), 87 ≤ n < 90 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc11 : ∀ n, n < 90 → 87 ≤ n → winsAll n := by decide +kernel

end GPn14
