/- GPn15W4.lean — window checks for GP(n,15), 54 ≤ n < 60 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc4 : ∀ n, n < 60 → 54 ≤ n → winsAll n := by decide +kernel

end GPn15
