/- GPn12W7.lean — window checks for GP(n,12), 68 ≤ n < 72 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc7 : ∀ n, n < 72 → 68 ≤ n → winsAll n := by decide +kernel

end GPn12
