/- GPn11W6.lean — window checks for GP(n,11), 61 ≤ n < 66 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc6 : ∀ n, n < 66 → 61 ≤ n → winsAll n := by decide +kernel

end GPn11
