/- GPn11W1.lean — window checks for GP(n,11), 23 ≤ n < 34 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc1 : ∀ n, n < 34 → 23 ≤ n → winsAll n := by decide +kernel

end GPn11
