/- GPn13W6.lean — window checks for GP(n,13), 63 ≤ n < 68 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc6 : ∀ n, n < 68 → 63 ≤ n → winsAll n := by decide +kernel

end GPn13
