/-
  GPn13.lean — generalized Petersen graphs GP(n,13), n ≥ 27: star edge colourings with 5 colours
  (colouring in GPn13T.lean, window checks for n < 72 in GPn13W1..7.lean; generated by search/gen_gpk.py).
-/
import GPn13W1
import GPn13W2
import GPn13W3
import GPn13W4
import GPn13W5
import GPn13W6
import GPn13W7

namespace GPn13
open BlockStar GPk

theorem Wsmall : ∀ n, n < 72 → 27 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 37
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 45
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 52
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 58
  · exact Wc4 n c4 (by omega)
  by_cases c5 : n < 63
  · exact Wc5 n c5 (by omega)
  by_cases c6 : n < 68
  · exact Wc6 n c6 (by omega)
  exact Wc7 n h1 (by omega)

theorem rep {n : Nat} (hn : 72 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 64 + n % 8 ∧ ∀ q, q ≤ 39 →
      idx (64 + n % 8) ((j' + q) % (64 + n % 8)) = idx n ((j + q) % n) := by
  have hm : (64 + n % 8) % 8 = n % 8 := by omega
  rcases (show j + 39 < n - n % 8 - 16 ∨ n - n % 8 - 16 ≤ j + 39 by omega) with c | c
  · refine ⟨j % 8, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (64 + n % 8) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,13).** For every `n ≥ 27`, `col n` is a star edge colouring of GP(n,13) with 5 colours. -/
theorem star5 (n : Nat) (hn : 27 ≤ n) : (gp n 13).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 72
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 64 + n % 8 < 72 := by omega
    refine ⟨fun _ => (), fun q => chi (64 + n % 8) ((j' + q) % (64 + n % 8)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 39 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 51 := by omega
    have h2 : ¬ 64 + n % 8 < 51 := by omega
    have hm : (64 + n % 8) % 8 = n % 8 := by omega
    show chi (64 + n % 8) ((j' + q) % (64 + n % 8)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 13).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,13), n ≥ 27: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 27 ≤ n) : StarFam (gp n 13) 5 :=
  ⟨subcubic n, gp_loopless n 13 (by decide) (by show max 1 13 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn13

#check @GPn13.star5
#check @GPn13.family
#print axioms GPn13.star5
#print axioms GPn13.family
