/- GPn14W2.lean — window checks for GP(n,14), 39 ≤ n < 47 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc2 : ∀ n, n < 47 → 39 ≤ n → winsAll n := by decide +kernel

end GPn14
