/-
  GPn14.lean — generalized Petersen graphs GP(n,14), n ≥ 29: star edge colourings with 5 colours
  (colouring in GPn14T.lean, window checks for n < 90 in GPn14W1..11.lean; generated by search/gen_gpk.py).
-/
import GPn14W1
import GPn14W2
import GPn14W3
import GPn14W4
import GPn14W5
import GPn14W6
import GPn14W7
import GPn14W8
import GPn14W9
import GPn14W10
import GPn14W11

namespace GPn14
open BlockStar GPk

theorem Wsmall : ∀ n, n < 90 → 29 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 39
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 47
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 54
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 60
  · exact Wc4 n c4 (by omega)
  by_cases c5 : n < 65
  · exact Wc5 n c5 (by omega)
  by_cases c6 : n < 70
  · exact Wc6 n c6 (by omega)
  by_cases c7 : n < 75
  · exact Wc7 n c7 (by omega)
  by_cases c8 : n < 79
  · exact Wc8 n c8 (by omega)
  by_cases c9 : n < 83
  · exact Wc9 n c9 (by omega)
  by_cases c10 : n < 87
  · exact Wc10 n c10 (by omega)
  exact Wc11 n h1 (by omega)

theorem rep {n : Nat} (hn : 90 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 80 + n % 10 ∧ ∀ q, q ≤ 42 →
      idx (80 + n % 10) ((j' + q) % (80 + n % 10)) = idx n ((j + q) % n) := by
  have hm : (80 + n % 10) % 10 = n % 10 := by omega
  rcases (show j + 42 < n - n % 10 - 20 ∨ n - n % 10 - 20 ≤ j + 42 by omega) with c | c
  · refine ⟨j % 10, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (80 + n % 10) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,14).** For every `n ≥ 29`, `col n` is a star edge colouring of GP(n,14) with 5 colours. -/
theorem star5 (n : Nat) (hn : 29 ≤ n) : (gp n 14).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 90
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 80 + n % 10 < 90 := by omega
    refine ⟨fun _ => (), fun q => chi (80 + n % 10) ((j' + q) % (80 + n % 10)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 42 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 59 := by omega
    have h2 : ¬ 80 + n % 10 < 59 := by omega
    have hm : (80 + n % 10) % 10 = n % 10 := by omega
    show chi (80 + n % 10) ((j' + q) % (80 + n % 10)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 14).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,14), n ≥ 29: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 29 ≤ n) : StarFam (gp n 14) 5 :=
  ⟨subcubic n, gp_loopless n 14 (by decide) (by show max 1 14 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn14

#check @GPn14.star5
#check @GPn14.family
#print axioms GPn14.star5
#print axioms GPn14.family
