/-
  GPn15.lean — generalized Petersen graphs GP(n,15), n ≥ 31: star edge colourings with 5 colours
  (colouring in GPn15T.lean, window checks for n < 80 in GPn15W1..9.lean; generated by search/gen_gpk.py).
-/
import GPn15W1
import GPn15W2
import GPn15W3
import GPn15W4
import GPn15W5
import GPn15W6
import GPn15W7
import GPn15W8
import GPn15W9

namespace GPn15
open BlockStar GPk

theorem Wsmall : ∀ n, n < 80 → 31 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 40
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 47
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 54
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 60
  · exact Wc4 n c4 (by omega)
  by_cases c5 : n < 65
  · exact Wc5 n c5 (by omega)
  by_cases c6 : n < 70
  · exact Wc6 n c6 (by omega)
  by_cases c7 : n < 75
  · exact Wc7 n c7 (by omega)
  by_cases c8 : n < 79
  · exact Wc8 n c8 (by omega)
  exact Wc9 n h1 (by omega)

theorem rep {n : Nat} (hn : 80 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 72 + n % 8 ∧ ∀ q, q ≤ 45 →
      idx (72 + n % 8) ((j' + q) % (72 + n % 8)) = idx n ((j + q) % n) := by
  have hm : (72 + n % 8) % 8 = n % 8 := by omega
  rcases (show j + 45 < n - n % 8 - 16 ∨ n - n % 8 - 16 ≤ j + 45 by omega) with c | c
  · refine ⟨j % 8, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (72 + n % 8) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,15).** For every `n ≥ 31`, `col n` is a star edge colouring of GP(n,15) with 5 colours. -/
theorem star5 (n : Nat) (hn : 31 ≤ n) : (gp n 15).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 80
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 72 + n % 8 < 80 := by omega
    refine ⟨fun _ => (), fun q => chi (72 + n % 8) ((j' + q) % (72 + n % 8)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 45 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 55 := by omega
    have h2 : ¬ 72 + n % 8 < 55 := by omega
    have hm : (72 + n % 8) % 8 = n % 8 := by omega
    show chi (72 + n % 8) ((j' + q) % (72 + n % 8)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 15).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,15), n ≥ 31: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 31 ≤ n) : StarFam (gp n 15) 5 :=
  ⟨subcubic n, gp_loopless n 15 (by decide) (by show max 1 15 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn15

#check @GPn15.star5
#check @GPn15.family
#print axioms GPn15.star5
#print axioms GPn15.family
