/- GPn15W7.lean — window checks for GP(n,15), 70 ≤ n < 75 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc7 : ∀ n, n < 75 → 70 ≤ n → winsAll n := by decide +kernel

end GPn15
