/- GPn14W8.lean — window checks for GP(n,14), 75 ≤ n < 79 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc8 : ∀ n, n < 79 → 75 ≤ n → winsAll n := by decide +kernel

end GPn14
