/- GPn14W3.lean — window checks for GP(n,14), 47 ≤ n < 54 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc3 : ∀ n, n < 54 → 47 ≤ n → winsAll n := by decide +kernel

end GPn14
