/-
  GPn1.lean — generalized Petersen graphs GP(n,1), n ≥ 4: star edge colourings with 5 colours
  (colouring in GPn1T.lean, window checks for n < 16 in GPn1W1..1.lean; generated by search/gen_gpk.py).
-/
import GPn1W1

namespace GPn1
open BlockStar GPk

theorem Wsmall : ∀ n, n < 16 → 4 ≤ n → winsAll n := by
  intro n h1 h2
  exact Wc1 n h1 (by omega)

theorem rep {n : Nat} (hn : 16 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 12 + n % 4 ∧ ∀ q, q ≤ 3 →
      idx (12 + n % 4) ((j' + q) % (12 + n % 4)) = idx n ((j + q) % n) := by
  have hm : (12 + n % 4) % 4 = n % 4 := by omega
  rcases (show j + 3 < n - n % 4 - 4 ∨ n - n % 4 - 4 ≤ j + 3 by omega) with c | c
  · refine ⟨j % 4, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (12 + n % 4) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,1).** For every `n ≥ 4`, `col n` is a star edge colouring of GP(n,1) with 5 colours. -/
theorem star5 (n : Nat) (hn : 4 ≤ n) : (gp n 1).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 16
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 12 + n % 4 < 16 := by omega
    refine ⟨fun _ => (), fun q => chi (12 + n % 4) ((j' + q) % (12 + n % 4)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 3 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 12 := by omega
    have h2 : ¬ 12 + n % 4 < 12 := by omega
    have hm : (12 + n % 4) % 4 = n % 4 := by omega
    show chi (12 + n % 4) ((j' + q) % (12 + n % 4)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 1).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,1), n ≥ 4: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 4 ≤ n) : StarFam (gp n 1) 5 :=
  ⟨subcubic n, gp_loopless n 1 (by decide) (by show max 1 1 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn1

#check @GPn1.star5
#check @GPn1.family
#print axioms GPn1.star5
#print axioms GPn1.family
