/- GPn11W8.lean — window checks for GP(n,11), 71 ≤ n < 72 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc8 : ∀ n, n < 72 → 71 ≤ n → winsAll n := by decide +kernel

end GPn11
