/- GPn15W8.lean — window checks for GP(n,15), 75 ≤ n < 79 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc8 : ∀ n, n < 79 → 75 ≤ n → winsAll n := by decide +kernel

end GPn15
