/- GPn15W1.lean — window checks for GP(n,15), 31 ≤ n < 40 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc1 : ∀ n, n < 40 → 31 ≤ n → winsAll n := by decide +kernel

end GPn15
