/- GPn14W4.lean — window checks for GP(n,14), 54 ≤ n < 60 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc4 : ∀ n, n < 60 → 54 ≤ n → winsAll n := by decide +kernel

end GPn14
