/- GPn11W7.lean — window checks for GP(n,11), 66 ≤ n < 71 (generated by search/gen_gpk.py) -/
import GPn11T

namespace GPn11

theorem Wc7 : ∀ n, n < 71 → 66 ≤ n → winsAll n := by decide +kernel

end GPn11
