/- GPn14W5.lean — window checks for GP(n,14), 60 ≤ n < 65 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc5 : ∀ n, n < 65 → 60 ≤ n → winsAll n := by decide +kernel

end GPn14
