/- GPn12W5.lean — window checks for GP(n,12), 57 ≤ n < 63 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc5 : ∀ n, n < 63 → 57 ≤ n → winsAll n := by decide +kernel

end GPn12
