/- GPn13W1.lean — window checks for GP(n,13), 27 ≤ n < 37 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc1 : ∀ n, n < 37 → 27 ≤ n → winsAll n := by decide +kernel

end GPn13
