/- GPn12W3.lean — window checks for GP(n,12), 44 ≤ n < 51 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc3 : ∀ n, n < 51 → 44 ≤ n → winsAll n := by decide +kernel

end GPn12
