/- GPn10W1.lean — window checks for GP(n,10), 21 ≤ n < 33 (generated by search/gen_gpk.py) -/
import GPn10T

namespace GPn10

theorem Wc1 : ∀ n, n < 33 → 21 ≤ n → winsAll n := by decide +kernel

end GPn10
