/- GPn12W4.lean — window checks for GP(n,12), 51 ≤ n < 57 (generated by search/gen_gpk.py) -/
import GPn12T

namespace GPn12

theorem Wc4 : ∀ n, n < 57 → 51 ≤ n → winsAll n := by decide +kernel

end GPn12
