/- GPn15W2.lean — window checks for GP(n,15), 40 ≤ n < 47 (generated by search/gen_gpk.py) -/
import GPn15T

namespace GPn15

theorem Wc2 : ∀ n, n < 47 → 40 ≤ n → winsAll n := by decide +kernel

end GPn15
