/- GPn14W1.lean — window checks for GP(n,14), 29 ≤ n < 39 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc1 : ∀ n, n < 39 → 29 ≤ n → winsAll n := by decide +kernel

end GPn14
