/- GPn14W7.lean — window checks for GP(n,14), 70 ≤ n < 75 (generated by search/gen_gpk.py) -/
import GPn14T

namespace GPn14

theorem Wc7 : ∀ n, n < 75 → 70 ≤ n → winsAll n := by decide +kernel

end GPn14
