/- GPn13W7.lean — window checks for GP(n,13), 68 ≤ n < 72 (generated by search/gen_gpk.py) -/
import GPn13T

namespace GPn13

theorem Wc7 : ∀ n, n < 72 → 68 ≤ n → winsAll n := by decide +kernel

end GPn13
