/-
  GPn2.lean — generalized Petersen graphs GP(n,2), n ≥ 5: star edge colourings with 5 colours
  (colouring in GPn2T.lean, window checks for n < 25 in GPn2W1..1.lean; generated by search/gen_gpk.py).
-/
import GPn2W1

namespace GPn2
open BlockStar GPk

theorem Wsmall : ∀ n, n < 25 → 5 ≤ n → winsAll n := by
  intro n h1 h2
  exact Wc1 n h1 (by omega)

theorem rep {n : Nat} (hn : 25 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 20 + n % 5 ∧ ∀ q, q ≤ 6 →
      idx (20 + n % 5) ((j' + q) % (20 + n % 5)) = idx n ((j + q) % n) := by
  have hm : (20 + n % 5) % 5 = n % 5 := by omega
  rcases (show j + 6 < n - n % 5 - 5 ∨ n - n % 5 - 5 ≤ j + 6 by omega) with c | c
  · refine ⟨j % 5, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (20 + n % 5) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,2).** For every `n ≥ 5`, `col n` is a star edge colouring of GP(n,2) with 5 colours. -/
theorem star5 (n : Nat) (hn : 5 ≤ n) : (gp n 2).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 25
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 20 + n % 5 < 25 := by omega
    refine ⟨fun _ => (), fun q => chi (20 + n % 5) ((j' + q) % (20 + n % 5)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 6 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 15 := by omega
    have h2 : ¬ 20 + n % 5 < 15 := by omega
    have hm : (20 + n % 5) % 5 = n % 5 := by omega
    show chi (20 + n % 5) ((j' + q) % (20 + n % 5)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 2).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,2), n ≥ 5: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 5 ≤ n) : StarFam (gp n 2) 5 :=
  ⟨subcubic n, gp_loopless n 2 (by decide) (by show max 1 2 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn2

#check @GPn2.star5
#check @GPn2.family
#print axioms GPn2.star5
#print axioms GPn2.family
