/-
  GPn3.lean — generalized Petersen graphs GP(n,3), n ≥ 7: star edge colourings with 5 colours
  (colouring in GPn3T.lean, window checks for n < 24 in GPn3W1..1.lean; generated by search/gen_gpk.py).
-/
import GPn3W1

namespace GPn3
open BlockStar GPk

theorem Wsmall : ∀ n, n < 24 → 7 ≤ n → winsAll n := by
  intro n h1 h2
  exact Wc1 n h1 (by omega)

theorem rep {n : Nat} (hn : 24 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 20 + n % 4 ∧ ∀ q, q ≤ 9 →
      idx (20 + n % 4) ((j' + q) % (20 + n % 4)) = idx n ((j + q) % n) := by
  have hm : (20 + n % 4) % 4 = n % 4 := by omega
  rcases (show j + 9 < n - n % 4 - 4 ∨ n - n % 4 - 4 ≤ j + 9 by omega) with c | c
  · refine ⟨j % 4, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (20 + n % 4) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,3).** For every `n ≥ 7`, `col n` is a star edge colouring of GP(n,3) with 5 colours. -/
theorem star5 (n : Nat) (hn : 7 ≤ n) : (gp n 3).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 24
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 20 + n % 4 < 24 := by omega
    refine ⟨fun _ => (), fun q => chi (20 + n % 4) ((j' + q) % (20 + n % 4)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 9 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 15 := by omega
    have h2 : ¬ 20 + n % 4 < 15 := by omega
    have hm : (20 + n % 4) % 4 = n % 4 := by omega
    show chi (20 + n % 4) ((j' + q) % (20 + n % 4)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 3).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,3), n ≥ 7: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 7 ≤ n) : StarFam (gp n 3) 5 :=
  ⟨subcubic n, gp_loopless n 3 (by decide) (by show max 1 3 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn3

#check @GPn3.star5
#check @GPn3.family
#print axioms GPn3.star5
#print axioms GPn3.family
