/-
  GPn4.lean — generalized Petersen graphs GP(n,4), n ≥ 9: star edge colourings with 5 colours
  (colouring in GPn4T.lean, window checks for n < 30 in GPn4W1..2.lean; generated by search/gen_gpk.py).
-/
import GPn4W1
import GPn4W2

namespace GPn4
open BlockStar GPk

theorem Wsmall : ∀ n, n < 30 → 9 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 27
  · exact Wc1 n c1 (by omega)
  exact Wc2 n h1 (by omega)

theorem rep {n : Nat} (hn : 30 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 25 + n % 5 ∧ ∀ q, q ≤ 12 →
      idx (25 + n % 5) ((j' + q) % (25 + n % 5)) = idx n ((j + q) % n) := by
  have hm : (25 + n % 5) % 5 = n % 5 := by omega
  rcases (show j + 12 < n - n % 5 - 5 ∨ n - n % 5 - 5 ≤ j + 12 by omega) with c | c
  · refine ⟨j % 5, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (25 + n % 5) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,4).** For every `n ≥ 9`, `col n` is a star edge colouring of GP(n,4) with 5 colours. -/
theorem star5 (n : Nat) (hn : 9 ≤ n) : (gp n 4).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 30
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 25 + n % 5 < 30 := by omega
    refine ⟨fun _ => (), fun q => chi (25 + n % 5) ((j' + q) % (25 + n % 5)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 12 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 19 := by omega
    have h2 : ¬ 25 + n % 5 < 19 := by omega
    have hm : (25 + n % 5) % 5 = n % 5 := by omega
    show chi (25 + n % 5) ((j' + q) % (25 + n % 5)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 4).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,4), n ≥ 9: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 9 ≤ n) : StarFam (gp n 4) 5 :=
  ⟨subcubic n, gp_loopless n 4 (by decide) (by show max 1 4 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn4

#check @GPn4.star5
#check @GPn4.family
#print axioms GPn4.star5
#print axioms GPn4.family
