/- GPn4W2.lean — window checks for GP(n,4), 27 ≤ n < 30 (generated by search/gen_gpk.py) -/
import GPn4T

namespace GPn4

theorem Wc2 : ∀ n, n < 30 → 27 ≤ n → winsAll n := by decide +kernel

end GPn4
