/- GPn5W1.lean — window checks for GP(n,5), 11 ≤ n < 28 (generated by search/gen_gpk.py) -/
import GPn5T

namespace GPn5

theorem Wc1 : ∀ n, n < 28 → 11 ≤ n → winsAll n := by decide +kernel

end GPn5
