/-
  GPn5.lean — generalized Petersen graphs GP(n,5), n ≥ 11: star edge colourings with 5 colours
  (colouring in GPn5T.lean, window checks for n < 36 in GPn5W1..2.lean; generated by search/gen_gpk.py).
-/
import GPn5W1
import GPn5W2

namespace GPn5
open BlockStar GPk

theorem Wsmall : ∀ n, n < 36 → 11 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 28
  · exact Wc1 n c1 (by omega)
  exact Wc2 n h1 (by omega)

theorem rep {n : Nat} (hn : 36 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 30 + n % 6 ∧ ∀ q, q ≤ 15 →
      idx (30 + n % 6) ((j' + q) % (30 + n % 6)) = idx n ((j + q) % n) := by
  have hm : (30 + n % 6) % 6 = n % 6 := by omega
  rcases (show j + 15 < n - n % 6 - 6 ∨ n - n % 6 - 6 ≤ j + 15 by omega) with c | c
  · refine ⟨j % 6, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (30 + n % 6) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,5).** For every `n ≥ 11`, `col n` is a star edge colouring of GP(n,5) with 5 colours. -/
theorem star5 (n : Nat) (hn : 11 ≤ n) : (gp n 5).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 36
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 30 + n % 6 < 36 := by omega
    refine ⟨fun _ => (), fun q => chi (30 + n % 6) ((j' + q) % (30 + n % 6)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 15 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 23 := by omega
    have h2 : ¬ 30 + n % 6 < 23 := by omega
    have hm : (30 + n % 6) % 6 = n % 6 := by omega
    show chi (30 + n % 6) ((j' + q) % (30 + n % 6)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 5).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,5), n ≥ 11: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 11 ≤ n) : StarFam (gp n 5) 5 :=
  ⟨subcubic n, gp_loopless n 5 (by decide) (by show max 1 5 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn5

#check @GPn5.star5
#check @GPn5.family
#print axioms GPn5.star5
#print axioms GPn5.family
