/- GPn5W2.lean — window checks for GP(n,5), 28 ≤ n < 36 (generated by search/gen_gpk.py) -/
import GPn5T

namespace GPn5

theorem Wc2 : ∀ n, n < 36 → 28 ≤ n → winsAll n := by decide +kernel

end GPn5
