/- GPn6W3.lean — window checks for GP(n,6), 38 ≤ n < 42 (generated by search/gen_gpk.py) -/
import GPn6T

namespace GPn6

theorem Wc3 : ∀ n, n < 42 → 38 ≤ n → winsAll n := by decide +kernel

end GPn6
