/- GPn6W1.lean — window checks for GP(n,6), 13 ≤ n < 28 (generated by search/gen_gpk.py) -/
import GPn6T

namespace GPn6

theorem Wc1 : ∀ n, n < 28 → 13 ≤ n → winsAll n := by decide +kernel

end GPn6
