/-
  GPn6.lean — generalized Petersen graphs GP(n,6), n ≥ 13: star edge colourings with 5 colours
  (colouring in GPn6T.lean, window checks for n < 42 in GPn6W1..3.lean; generated by search/gen_gpk.py).
-/
import GPn6W1
import GPn6W2
import GPn6W3

namespace GPn6
open BlockStar GPk

theorem Wsmall : ∀ n, n < 42 → 13 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 28
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 38
  · exact Wc2 n c2 (by omega)
  exact Wc3 n h1 (by omega)

theorem rep {n : Nat} (hn : 42 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 35 + n % 7 ∧ ∀ q, q ≤ 18 →
      idx (35 + n % 7) ((j' + q) % (35 + n % 7)) = idx n ((j + q) % n) := by
  have hm : (35 + n % 7) % 7 = n % 7 := by omega
  rcases (show j + 18 < n - n % 7 - 7 ∨ n - n % 7 - 7 ≤ j + 18 by omega) with c | c
  · refine ⟨j % 7, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (35 + n % 7) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,6).** For every `n ≥ 13`, `col n` is a star edge colouring of GP(n,6) with 5 colours. -/
theorem star5 (n : Nat) (hn : 13 ≤ n) : (gp n 6).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 42
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 35 + n % 7 < 42 := by omega
    refine ⟨fun _ => (), fun q => chi (35 + n % 7) ((j' + q) % (35 + n % 7)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 18 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 27 := by omega
    have h2 : ¬ 35 + n % 7 < 27 := by omega
    have hm : (35 + n % 7) % 7 = n % 7 := by omega
    show chi (35 + n % 7) ((j' + q) % (35 + n % 7)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 6).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,6), n ≥ 13: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 13 ≤ n) : StarFam (gp n 6) 5 :=
  ⟨subcubic n, gp_loopless n 6 (by decide) (by show max 1 6 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn6

#check @GPn6.star5
#check @GPn6.family
#print axioms GPn6.star5
#print axioms GPn6.family
