/- GPn6W2.lean — window checks for GP(n,6), 28 ≤ n < 38 (generated by search/gen_gpk.py) -/
import GPn6T

namespace GPn6

theorem Wc2 : ∀ n, n < 38 → 28 ≤ n → winsAll n := by decide +kernel

end GPn6
