/- GPn7W1.lean — window checks for GP(n,7), 15 ≤ n < 29 (generated by search/gen_gpk.py) -/
import GPn7T

namespace GPn7

theorem Wc1 : ∀ n, n < 29 → 15 ≤ n → winsAll n := by decide +kernel

end GPn7
