/- GPn7W3.lean — window checks for GP(n,7), 39 ≤ n < 47 (generated by search/gen_gpk.py) -/
import GPn7T

namespace GPn7

theorem Wc3 : ∀ n, n < 47 → 39 ≤ n → winsAll n := by decide +kernel

end GPn7
