/- GPn7W4.lean — window checks for GP(n,7), 47 ≤ n < 48 (generated by search/gen_gpk.py) -/
import GPn7T

namespace GPn7

theorem Wc4 : ∀ n, n < 48 → 47 ≤ n → winsAll n := by decide +kernel

end GPn7
