/-
  GPn7.lean — generalized Petersen graphs GP(n,7), n ≥ 15: star edge colourings with 5 colours
  (colouring in GPn7T.lean, window checks for n < 48 in GPn7W1..4.lean; generated by search/gen_gpk.py).
-/
import GPn7W1
import GPn7W2
import GPn7W3
import GPn7W4

namespace GPn7
open BlockStar GPk

theorem Wsmall : ∀ n, n < 48 → 15 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 29
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 39
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 47
  · exact Wc3 n c3 (by omega)
  exact Wc4 n h1 (by omega)

theorem rep {n : Nat} (hn : 48 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 40 + n % 8 ∧ ∀ q, q ≤ 21 →
      idx (40 + n % 8) ((j' + q) % (40 + n % 8)) = idx n ((j + q) % n) := by
  have hm : (40 + n % 8) % 8 = n % 8 := by omega
  rcases (show j + 21 < n - n % 8 - 8 ∨ n - n % 8 - 8 ≤ j + 21 by omega) with c | c
  · refine ⟨j % 8, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (40 + n % 8) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,7).** For every `n ≥ 15`, `col n` is a star edge colouring of GP(n,7) with 5 colours. -/
theorem star5 (n : Nat) (hn : 15 ≤ n) : (gp n 7).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 48
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 40 + n % 8 < 48 := by omega
    refine ⟨fun _ => (), fun q => chi (40 + n % 8) ((j' + q) % (40 + n % 8)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 21 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 31 := by omega
    have h2 : ¬ 40 + n % 8 < 31 := by omega
    have hm : (40 + n % 8) % 8 = n % 8 := by omega
    show chi (40 + n % 8) ((j' + q) % (40 + n % 8)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 7).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,7), n ≥ 15: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 15 ≤ n) : StarFam (gp n 7) 5 :=
  ⟨subcubic n, gp_loopless n 7 (by decide) (by show max 1 7 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn7

#check @GPn7.star5
#check @GPn7.family
#print axioms GPn7.star5
#print axioms GPn7.family
