/- GPn7W2.lean — window checks for GP(n,7), 29 ≤ n < 39 (generated by search/gen_gpk.py) -/
import GPn7T

namespace GPn7

theorem Wc2 : ∀ n, n < 39 → 29 ≤ n → winsAll n := by decide +kernel

end GPn7
