/- GPn8W2.lean — window checks for GP(n,8), 31 ≤ n < 40 (generated by search/gen_gpk.py) -/
import GPn8T

namespace GPn8

theorem Wc2 : ∀ n, n < 40 → 31 ≤ n → winsAll n := by decide +kernel

end GPn8
