/- GPn8W4.lean — window checks for GP(n,8), 47 ≤ n < 54 (generated by search/gen_gpk.py) -/
import GPn8T

namespace GPn8

theorem Wc4 : ∀ n, n < 54 → 47 ≤ n → winsAll n := by decide +kernel

end GPn8
