/- GPn8W1.lean — window checks for GP(n,8), 17 ≤ n < 31 (generated by search/gen_gpk.py) -/
import GPn8T

namespace GPn8

theorem Wc1 : ∀ n, n < 31 → 17 ≤ n → winsAll n := by decide +kernel

end GPn8
