/-
  GPn8.lean — generalized Petersen graphs GP(n,8), n ≥ 17: star edge colourings with 5 colours
  (colouring in GPn8T.lean, window checks for n < 54 in GPn8W1..4.lean; generated by search/gen_gpk.py).
-/
import GPn8W1
import GPn8W2
import GPn8W3
import GPn8W4

namespace GPn8
open BlockStar GPk

theorem Wsmall : ∀ n, n < 54 → 17 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 31
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 40
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 47
  · exact Wc3 n c3 (by omega)
  exact Wc4 n h1 (by omega)

theorem rep {n : Nat} (hn : 54 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 45 + n % 9 ∧ ∀ q, q ≤ 24 →
      idx (45 + n % 9) ((j' + q) % (45 + n % 9)) = idx n ((j + q) % n) := by
  have hm : (45 + n % 9) % 9 = n % 9 := by omega
  rcases (show j + 24 < n - n % 9 - 9 ∨ n - n % 9 - 9 ≤ j + 24 by omega) with c | c
  · refine ⟨j % 9, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (45 + n % 9) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,8).** For every `n ≥ 17`, `col n` is a star edge colouring of GP(n,8) with 5 colours. -/
theorem star5 (n : Nat) (hn : 17 ≤ n) : (gp n 8).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 54
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 45 + n % 9 < 54 := by omega
    refine ⟨fun _ => (), fun q => chi (45 + n % 9) ((j' + q) % (45 + n % 9)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 24 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 35 := by omega
    have h2 : ¬ 45 + n % 9 < 35 := by omega
    have hm : (45 + n % 9) % 9 = n % 9 := by omega
    show chi (45 + n % 9) ((j' + q) % (45 + n % 9)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 8).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,8), n ≥ 17: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 17 ≤ n) : StarFam (gp n 8) 5 :=
  ⟨subcubic n, gp_loopless n 8 (by decide) (by show max 1 8 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn8

#check @GPn8.star5
#check @GPn8.family
#print axioms GPn8.star5
#print axioms GPn8.family
