/- GPn8W3.lean — window checks for GP(n,8), 40 ≤ n < 47 (generated by search/gen_gpk.py) -/
import GPn8T

namespace GPn8

theorem Wc3 : ∀ n, n < 47 → 40 ≤ n → winsAll n := by decide +kernel

end GPn8
