/- GPn9W2.lean — window checks for GP(n,9), 32 ≤ n < 41 (generated by search/gen_gpk.py) -/
import GPn9T

namespace GPn9

theorem Wc2 : ∀ n, n < 41 → 32 ≤ n → winsAll n := by decide +kernel

end GPn9
