/- GPn9W1.lean — window checks for GP(n,9), 19 ≤ n < 32 (generated by search/gen_gpk.py) -/
import GPn9T

namespace GPn9

theorem Wc1 : ∀ n, n < 32 → 19 ≤ n → winsAll n := by decide +kernel

end GPn9
