/- GPn9W5.lean — window checks for GP(n,9), 54 ≤ n < 60 (generated by search/gen_gpk.py) -/
import GPn9T

namespace GPn9

theorem Wc5 : ∀ n, n < 60 → 54 ≤ n → winsAll n := by decide +kernel

end GPn9
