/- GPn9W4.lean — window checks for GP(n,9), 48 ≤ n < 54 (generated by search/gen_gpk.py) -/
import GPn9T

namespace GPn9

theorem Wc4 : ∀ n, n < 54 → 48 ≤ n → winsAll n := by decide +kernel

end GPn9
