/- GPn9W3.lean — window checks for GP(n,9), 41 ≤ n < 48 (generated by search/gen_gpk.py) -/
import GPn9T

namespace GPn9

theorem Wc3 : ∀ n, n < 48 → 41 ≤ n → winsAll n := by decide +kernel

end GPn9
