/-
  GPn9.lean — generalized Petersen graphs GP(n,9), n ≥ 19: star edge colourings with 5 colours
  (colouring in GPn9T.lean, window checks for n < 60 in GPn9W1..5.lean; generated by search/gen_gpk.py).
-/
import GPn9W1
import GPn9W2
import GPn9W3
import GPn9W4
import GPn9W5

namespace GPn9
open BlockStar GPk

theorem Wsmall : ∀ n, n < 60 → 19 ≤ n → winsAll n := by
  intro n h1 h2
  by_cases c1 : n < 32
  · exact Wc1 n c1 (by omega)
  by_cases c2 : n < 41
  · exact Wc2 n c2 (by omega)
  by_cases c3 : n < 48
  · exact Wc3 n c3 (by omega)
  by_cases c4 : n < 54
  · exact Wc4 n c4 (by omega)
  exact Wc5 n h1 (by omega)

theorem rep {n : Nat} (hn : 60 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 50 + n % 10 ∧ ∀ q, q ≤ 27 →
      idx (50 + n % 10) ((j' + q) % (50 + n % 10)) = idx n ((j + q) % n) := by
  have hm : (50 + n % 10) % 10 = n % 10 := by omega
  rcases (show j + 27 < n - n % 10 - 10 ∨ n - n % 10 - 10 ≤ j + 27 by omega) with c | c
  · refine ⟨j % 10, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + (50 + n % 10) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,9).** For every `n ≥ 19`, `col n` is a star edge colouring of GP(n,9) with 5 colours. -/
theorem star5 (n : Nat) (hn : 19 ≤ n) : (gp n 9).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 60
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 50 + n % 10 < 60 := by omega
    refine ⟨fun _ => (), fun q => chi (50 + n % 10) ((j' + q) % (50 + n % 10)), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 27 := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < 39 := by omega
    have h2 : ¬ 50 + n % 10 < 39 := by omega
    have hm : (50 + n % 10) % 10 = n % 10 := by omega
    show chi (50 + n % 10) ((j' + q) % (50 + n % 10)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n 9).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,9), n ≥ 19: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : 19 ≤ n) : StarFam (gp n 9) 5 :=
  ⟨subcubic n, gp_loopless n 9 (by decide) (by show max 1 9 < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end GPn9

#check @GPn9.star5
#check @GPn9.family
#print axioms GPn9.star5
#print axioms GPn9.family
