/-
  GPPeriodic.lean — generalized Petersen graphs GP(n,k) (general k) as cyclic block graphs, the criterion for
  periodic colourings, and the families GP(10m,4), GP(14m,6), GP(17m,8), GP(22m,10), GP(26m,12), GP(30m,14) (m ≥ 1):
  star edge colourings with 5 colours.

  GP(n,k): vertices u_i, v_i (i ∈ Z/n); edges u_i u_{i+1}, u_i v_i, v_i v_{i+k}.  Encoding: u_i = 2i, v_i = 2i+1
  in `Fin (n * 2)`; edge 3i: u_i u_{i+1}, 3i+1: u_i v_i, 3i+2: v_i v_{i+k} in `Fin (n * 3)`.
  The colourings (period L, block i gets row i mod L of the table, columns: outer, spoke, inner edge) are those of
  the star6 facts f8e1edfe45707104 (k = 4), 6309f733d6da8cd6 (k = 6), a491fe56b9f2d831 (k = 8, 10, 12, 14), colours
  shifted to 0..4.  (Generated by gen_gpper.py from the tables of these facts.)
-/
import BlockProps
import GPetersen2

namespace GPk
open BlockStar GPetersen2

def kjmp (k s : Nat) : Nat := match s with
  | 0 => 1 | 1 => 0 | _ => k

/-- wiring of GP(n,k): vertex types u = 0, v = 1; edge types 0: u_i u_{i+1}, 1: u_i v_i, 2: v_i v_{i+k} -/
def gpkWir (k : Nat) : Wir Unit 2 3 where
  D := max 1 k
  src := fun _ s => psrc s
  jmp := fun _ s => kjmp k s
  dst := fun _ s => pdst s
  hsrc := by intro w s; unfold psrc; split <;> omega
  hdst := by intro w s; unfold pdst; split <;> omega
  hjmp := by intro w s; unfold kjmp; split <;> omega
  jumps := [0, 1, k]
  hjmps := by intro w s; unfold kjmp; split <;> simp

/-- the generalized Petersen graph GP(n,k) -/
def gp (n k : Nat) : MGraph := BG (gpkWir k) n (fun _ => ())

/-- colour (0..4) of the edge type `s` in a block with pattern `c = [outer, spoke, inner]` -/
def ct (c : List Nat) (s : Nat) : Nat := (c.getD s 0) % 5

theorem ct_lt : ∀ c s, ct c s < 5 := fun _ _ => Nat.mod_lt _ (by decide)

/-- the periodic colouring with table `tab`: block `J` gets the pattern `tab[J mod tab.length]` -/
def pcol (tab : List (List Nat)) {m : Nat} : Fin m → Fin 5 :=
  bcol 3 ct ct_lt (fun J => tab.getD (J % tab.length) [])

/-- all windows of the periodic sequence pass the window check -/
abbrev perOK (k : Nat) (tab : List (List Nat)) : Prop :=
  ∀ j, j < tab.length → winOK (gpkWir k) ct (fun _ => ()) (fun p => tab.getD ((j + p) % tab.length) []) = true

/-- a periodic colouring whose windows pass the check is a star edge colouring of GP(L m, k), L the period -/
theorem periodic_star (k : Nat) (tab : List (List Nat)) (hL : 0 < tab.length) (h : perOK k tab) (m : Nat) :
    (gp (tab.length * m) k).Star 5 (pcol tab) := by
  apply star_of_windows
  intro j hj
  refine ⟨fun _ => (), fun p => tab.getD ((j % tab.length + p) % tab.length) [], ?_,
    h (j % tab.length) (Nat.mod_lt _ hL)⟩
  intro p _
  refine ⟨rfl, ?_⟩
  show tab.getD ((j % tab.length + p) % tab.length) [] = tab.getD ((j + p) % (tab.length * m) % tab.length) []
  rw [Nat.mod_mul_right_mod, Nat.mod_add_mod]

theorem gp_loopless (n k : Nat) (hk : 0 < k) (hn : max 1 k < n) : (gp n k).Loopless := by
  apply BG_loopless
  · exact hn
  · intro w s hs hz
    have hz' : kjmp k s = 0 := hz
    show psrc s ≠ pdst s
    have hs' : s < 3 := hs
    interval_cases s
    · have h1 : kjmp k 0 = 1 := rfl
      omega
    · decide
    · have h1 : kjmp k 2 = k := rfl
      omega

/-- the statement of `Families.StarFamily` (repeated here to keep the import graph small) -/
def StarFam (G : MGraph) (k : Nat) : Prop :=
  G.Subcubic ∧ G.Loopless ∧ (∀ P : Fin G.m → Prop, MGraph.Colourable P k) ∧
    (∀ P : Fin G.m → Prop, MGraph.Colourable P 6)


/-- period-10 colouring of GP(10m,4) (fact f8e1edfe45707104) -/
def tab4 : List (List Nat) :=
  [[1, 0, 2], [0, 3, 2], [3, 2, 1], [1, 2, 0], [3, 4, 0], [0, 4, 1],
   [2, 3, 4], [1, 3, 4], [2, 3, 4], [4, 3, 4]]

theorem per4 : perOK 4 tab4 := by decide +kernel

theorem subcubic4 (n : Nat) : (gp n 4).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(10m,4), m ≥ 1**: `pcol tab4` is a star edge colouring with 5 colours -/
theorem star4 (m : Nat) : (gp (10 * m) 4).Star 5 (pcol tab4) :=
  periodic_star 4 tab4 (by decide) per4 m

theorem family4 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (10 * m) 4) 5 :=
  ⟨subcubic4 _, gp_loopless _ _ (by decide) (by show max 1 4 < 10 * m; omega),
    colourable_of_star (star4 m) (Nat.le_refl 5), colourable_of_star (star4 m) (by decide)⟩


/-- period-14 colouring of GP(14m,6) (fact 6309f733d6da8cd6) -/
def tab6 : List (List Nat) :=
  [[0, 1, 3], [1, 2, 3], [2, 3, 0], [0, 3, 1], [3, 2, 1], [1, 2, 0],
   [4, 2, 0], [1, 0, 1], [2, 3, 4], [0, 3, 4], [2, 3, 4], [1, 3, 4],
   [2, 3, 4], [4, 3, 4]]

theorem per6 : perOK 6 tab6 := by decide +kernel

theorem subcubic6 (n : Nat) : (gp n 6).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(14m,6), m ≥ 1**: `pcol tab6` is a star edge colouring with 5 colours -/
theorem star6 (m : Nat) : (gp (14 * m) 6).Star 5 (pcol tab6) :=
  periodic_star 6 tab6 (by decide) per6 m

theorem family6 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (14 * m) 6) 5 :=
  ⟨subcubic6 _, gp_loopless _ _ (by decide) (by show max 1 6 < 14 * m; omega),
    colourable_of_star (star6 m) (Nat.le_refl 5), colourable_of_star (star6 m) (by decide)⟩


/-- period-17 colouring of GP(17m,8) (fact a491fe56b9f2d831) -/
def tab8 : List (List Nat) :=
  [[4, 1, 2], [2, 0, 3], [0, 3, 1], [1, 3, 2], [4, 2, 0], [3, 0, 1],
   [0, 1, 2], [1, 2, 0], [4, 3, 4], [2, 1, 0], [0, 3, 4], [1, 3, 4],
   [2, 3, 4], [0, 3, 4], [1, 3, 4], [2, 3, 4], [3, 0, 1]]

theorem per8 : perOK 8 tab8 := by decide +kernel

theorem subcubic8 (n : Nat) : (gp n 8).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(17m,8), m ≥ 1**: `pcol tab8` is a star edge colouring with 5 colours -/
theorem star8 (m : Nat) : (gp (17 * m) 8).Star 5 (pcol tab8) :=
  periodic_star 8 tab8 (by decide) per8 m

theorem family8 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (17 * m) 8) 5 :=
  ⟨subcubic8 _, gp_loopless _ _ (by decide) (by show max 1 8 < 17 * m; omega),
    colourable_of_star (star8 m) (Nat.le_refl 5), colourable_of_star (star8 m) (by decide)⟩


/-- period-22 colouring of GP(22m,10) (fact a491fe56b9f2d831) -/
def tab10 : List (List Nat) :=
  [[0, 1, 3], [1, 3, 2], [2, 3, 0], [0, 3, 1], [3, 2, 1], [1, 2, 0],
   [2, 3, 0], [0, 3, 1], [3, 2, 1], [1, 2, 0], [4, 2, 0], [1, 0, 1],
   [2, 3, 4], [0, 3, 4], [2, 3, 4], [1, 3, 4], [2, 3, 4], [0, 3, 4],
   [2, 3, 4], [1, 3, 4], [2, 3, 4], [4, 3, 4]]

theorem per10 : perOK 10 tab10 := by decide +kernel

theorem subcubic10 (n : Nat) : (gp n 10).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(22m,10), m ≥ 1**: `pcol tab10` is a star edge colouring with 5 colours -/
theorem star10 (m : Nat) : (gp (22 * m) 10).Star 5 (pcol tab10) :=
  periodic_star 10 tab10 (by decide) per10 m

theorem family10 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (22 * m) 10) 5 :=
  ⟨subcubic10 _, gp_loopless _ _ (by decide) (by show max 1 10 < 22 * m; omega),
    colourable_of_star (star10 m) (Nat.le_refl 5), colourable_of_star (star10 m) (by decide)⟩


/-- period-26 colouring of GP(26m,12) (fact a491fe56b9f2d831) -/
def tab12 : List (List Nat) :=
  [[1, 0, 2], [0, 3, 2], [2, 3, 1], [1, 3, 0], [2, 3, 0], [0, 3, 1],
   [2, 3, 1], [1, 3, 0], [2, 3, 0], [0, 3, 1], [3, 2, 1], [1, 2, 0],
   [3, 4, 0], [0, 4, 1], [2, 3, 4], [1, 3, 4], [2, 3, 4], [0, 3, 4],
   [2, 3, 4], [1, 3, 4], [2, 3, 4], [0, 3, 4], [2, 3, 4], [1, 3, 4],
   [2, 3, 4], [4, 3, 4]]

theorem per12 : perOK 12 tab12 := by decide +kernel

theorem subcubic12 (n : Nat) : (gp n 12).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(26m,12), m ≥ 1**: `pcol tab12` is a star edge colouring with 5 colours -/
theorem star12 (m : Nat) : (gp (26 * m) 12).Star 5 (pcol tab12) :=
  periodic_star 12 tab12 (by decide) per12 m

theorem family12 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (26 * m) 12) 5 :=
  ⟨subcubic12 _, gp_loopless _ _ (by decide) (by show max 1 12 < 26 * m; omega),
    colourable_of_star (star12 m) (Nat.le_refl 5), colourable_of_star (star12 m) (by decide)⟩


/-- period-30 colouring of GP(30m,14) (fact a491fe56b9f2d831) -/
def tab14 : List (List Nat) :=
  [[0, 1, 3], [1, 3, 2], [2, 3, 0], [0, 3, 1], [2, 3, 1], [1, 3, 0],
   [2, 3, 0], [0, 3, 1], [3, 2, 1], [1, 2, 0], [2, 3, 0], [0, 3, 1],
   [3, 2, 1], [1, 2, 0], [4, 2, 0], [1, 0, 1], [2, 3, 4], [0, 3, 4],
   [2, 3, 4], [1, 3, 4], [2, 3, 4], [0, 3, 4], [2, 3, 4], [1, 3, 4],
   [2, 3, 4], [0, 3, 4], [2, 3, 4], [1, 3, 4], [2, 3, 4], [4, 3, 4]]

theorem per14 : perOK 14 tab14 := by decide +kernel

theorem subcubic14 (n : Nat) : (gp n 14).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- **GP(30m,14), m ≥ 1**: `pcol tab14` is a star edge colouring with 5 colours -/
theorem star14 (m : Nat) : (gp (30 * m) 14).Star 5 (pcol tab14) :=
  periodic_star 14 tab14 (by decide) per14 m

theorem family14 (m : Nat) (hm : 1 ≤ m) : StarFam (gp (30 * m) 14) 5 :=
  ⟨subcubic14 _, gp_loopless _ _ (by decide) (by show max 1 14 < 30 * m; omega),
    colourable_of_star (star14 m) (Nat.le_refl 5), colourable_of_star (star14 m) (by decide)⟩


end GPk

#check @GPk.star4
#check @GPk.family4
#check @GPk.star6
#check @GPk.family6
#check @GPk.star8
#check @GPk.family8
#check @GPk.star10
#check @GPk.family10
#check @GPk.star12
#check @GPk.family12
#check @GPk.star14
#check @GPk.family14
#print axioms GPk.star4
#print axioms GPk.family4
#print axioms GPk.star6
#print axioms GPk.family6
#print axioms GPk.star8
#print axioms GPk.family8
#print axioms GPk.star10
#print axioms GPk.family10
#print axioms GPk.star12
#print axioms GPk.family12
#print axioms GPk.star14
#print axioms GPk.family14
