/-
  Mobius.lean — Möbius ladders M_n (n rungs, 2n vertices), n ≥ 4: star edge colourings with 5 colours.
  (M_3 = K_{3,3} has star chromatic index 6.)

  M_n: cycle c_0 … c_{2n-1} with the chords c_i c_{i+n}.  Encoding as a cyclic block graph: block i = {t_i, b_i} with
  t_i = c_i = 2i, b_i = c_{i+n} = 2i+1 in `Fin (n * 2)`; edges of block i: 3i: t_i t_{i+1}, 3i+1: t_i b_i (the chord),
  3i+2: b_i b_{i+1} for i ≤ n−2, and for the last block (wiring kind 1): 3i: t_{n-1} b_0, 3i+2: b_{n-1} t_0.
  Colouring: for n ≥ 12 a periodic part of period 4 followed by a seam of length n mod 4 + 4; explicit colourings
  for 4 ≤ n < 12; a pattern is [t-edge, chord, b-edge] with colours 0..4.  The tables were found by a SAT search on
  2026-10-02 (search/mlsearch.py, search/ml.json); generated by search/gen_ml.py.
-/
import Families
import GPPeriodic

namespace Mobius
open BlockStar SeamSeq GPk

def msrc (s : Nat) : Nat := match s with
  | 0 => 0 | 1 => 0 | _ => 1
def mjmp (s : Nat) : Nat := match s with
  | 1 => 0 | _ => 1
/-- head type of the edge type `s` in a block of wiring kind `w` (`w = 0`: normal, otherwise twisted) -/
def mdst (w s : Nat) : Nat := match s with
  | 0 => if w = 0 then 0 else 1
  | 1 => 1
  | _ => if w = 0 then 1 else 0

def mWir : Wir Nat 2 3 where
  D := 1
  src := fun _ s => msrc s
  jmp := fun _ s => mjmp s
  dst := mdst
  hsrc := by intro w s; unfold msrc; split <;> omega
  hdst := by intro w s; unfold mdst; split <;> first | omega | (split <;> omega)
  hjmp := by intro w s; unfold mjmp; split <;> omega
  jumps := [0, 1]
  hjmps := by intro w s; unfold mjmp; split <;> decide

/-- the Möbius ladder M_n: the last block `J = n - 1` is wired with the twist (`tw n J = 1`) -/
def mobius (n : Nat) : MGraph := BG mWir n (fun J => tw n J)

/-- row r (r = n mod 4): P0..P3 followed by the seam for this residue -/
def tabs : List (List (List Nat)) :=
  [[[1, 0, 2], [2, 3, 1], [4, 0, 4], [2, 3, 1], [1, 0, 3], [3, 4, 2],
    [2, 0, 1], [4, 3, 4]],
   [[1, 0, 2], [2, 3, 1], [4, 0, 4], [2, 3, 1], [1, 0, 2], [2, 4, 1],
    [3, 0, 3], [1, 4, 2], [4, 3, 4]],
   [[1, 0, 2], [2, 3, 1], [4, 0, 4], [2, 3, 1], [0, 3, 0], [1, 4, 2],
    [2, 3, 1], [0, 4, 0], [1, 3, 2], [4, 3, 4]],
   [[1, 0, 2], [2, 3, 1], [4, 0, 4], [2, 3, 1], [3, 0, 3], [1, 4, 2],
    [0, 4, 3], [2, 4, 1], [0, 4, 3], [1, 4, 2], [4, 3, 4]]]

/-- explicit colourings for n = 4..11 (row n - 4) -/
def smallTab : List (List (List Nat)) :=
  [[[0, 1, 0], [2, 3, 2], [0, 1, 0], [4, 3, 4]],
   [[0, 1, 2], [2, 4, 0], [3, 1, 3], [0, 4, 2], [3, 4, 3]],
   [[0, 1, 0], [2, 3, 2], [0, 1, 0], [3, 4, 3], [0, 1, 0], [4, 2, 4]],
   [[1, 0, 2], [0, 3, 1], [3, 2, 0], [2, 4, 1], [0, 4, 3], [1, 4, 2],
    [4, 3, 4]],
   [[0, 1, 0], [2, 3, 2], [0, 1, 0], [3, 4, 3], [0, 1, 0], [2, 4, 2],
    [0, 1, 0], [4, 3, 4]],
   [[1, 0, 2], [2, 3, 1], [0, 4, 0], [1, 3, 2], [0, 4, 3], [2, 4, 1],
    [0, 4, 3], [1, 4, 2], [4, 3, 4]],
   [[0, 1, 0], [2, 3, 2], [0, 1, 0], [3, 4, 3], [0, 1, 0], [2, 4, 2],
    [0, 1, 0], [3, 4, 3], [0, 1, 0], [4, 2, 4]],
   [[1, 0, 2], [0, 3, 1], [3, 2, 0], [2, 4, 1], [0, 4, 3], [1, 4, 2],
    [0, 4, 3], [2, 4, 1], [0, 4, 3], [1, 4, 2], [4, 3, 4]]]

def idx (n J : Nat) : Nat :=
  if J < n - n % 4 - 4 then J % 4 else 4 + (J - (n - n % 4 - 4))

/-- the pattern of block `J` -/
def chi (n J : Nat) : List Nat :=
  if n < 12 then (smallTab.getD (n - 4) []).getD J [] else (tabs.getD (n % 4) []).getD (idx n J) []

/-- the colouring -/
def col (n : Nat) : Fin (mobius n).m → Fin 5 := bcol 3 ct ct_lt (chi n)

abbrev winsAll (n : Nat) : Prop :=
  ∀ j, j < n → winOK mWir ct (fun q => tw n ((j + q) % n)) (fun q => chi n ((j + q) % n)) = true

theorem Wsmall : ∀ n, n < 16 → 4 ≤ n → winsAll n := by decide +kernel

theorem rep {n : Nat} (hn : 16 ≤ n) {j : Nat} (hj : j < n) :
    ∃ j', j' < 12 + n % 4 ∧ ∀ q, q ≤ 3 →
      tw (12 + n % 4) ((j' + q) % (12 + n % 4)) = tw n ((j + q) % n) ∧
      idx (12 + n % 4) ((j' + q) % (12 + n % 4)) = idx n ((j + q) % n) := by
  have hm : (12 + n % 4) % 4 = n % 4 := by omega
  rcases (show j + 3 < n - n % 4 - 4 ∨ n - n % 4 - 4 ≤ j + 3 by omega) with c | c
  · refine ⟨j % 4, by omega, ?_⟩
    intro q hq
    rw [modc hj (by omega), modc (by omega) (by omega)]
    simp only [idx, tw, hm]
    constructor <;> split_ifs <;> omega
  · refine ⟨j + (12 + n % 4) - n, by omega, ?_⟩
    intro q hq
    rw [modc hj (by omega), modc (by omega) (by omega)]
    simp only [idx, tw, hm]
    constructor <;> split_ifs <;> omega

/-- **Möbius ladders.** For every `n ≥ 4`, `col n` is a star edge colouring of M_n with 5 colours. -/
theorem star5 (n : Nat) (hn : 4 ≤ n) : (mobius n).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < 16
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : 12 + n % 4 < 16 := by omega
    refine ⟨fun q => tw (12 + n % 4) ((j' + q) % (12 + n % 4)),
      fun q => chi (12 + n % 4) ((j' + q) % (12 + n % 4)), ?_, Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 3 := hq
    obtain ⟨e1, e2⟩ := hrep q hq'
    refine ⟨e1, ?_⟩
    have h1 : ¬ n < 12 := by omega
    have h2 : ¬ 12 + n % 4 < 12 := by omega
    have hm : (12 + n % 4) % 4 = n % 4 := by omega
    show chi (12 + n % 4) ((j' + q) % (12 + n % 4)) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e2]

theorem mobius_loopless (n : Nat) (hn : 2 ≤ n) : (mobius n).Loopless := by
  apply BG_loopless
  · show 1 < n
    omega
  · intro w s hs hz
    have hz' : mjmp s = 0 := hz
    show msrc s ≠ mdst w s
    have hs' : s < 3 := hs
    interval_cases s <;> first | exact absurd hz' (by decide) | simp [msrc, mdst]

theorem mobius_subcubic (n : Nat) (hn : 2 ≤ n) : (mobius n).Subcubic := by
  apply BG_subcubic
  intro j hj
  have two : ∀ q, q ≤ mWir.D → q = 0 ∨ q = 1 := by
    intro q hq
    have hq' : q ≤ 1 := hq
    omega
  rcases FlowerSnark.tw_cases hn hj with ⟨h0, h1⟩ | ⟨h0, h1⟩ | ⟨h0, h1⟩
  · refine ⟨fun q => [1, 0].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm
  · refine ⟨fun q => [0, 1].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm
  · refine ⟨fun q => [0, 0].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm

/-- Möbius ladders M_n, n ≥ 4: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem mobius_family (n : Nat) (hn : 4 ≤ n) : StarFamily (mobius n) 5 :=
  ⟨mobius_subcubic n (by omega), mobius_loopless n (by omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end Mobius

#check @Mobius.star5
#check @Mobius.mobius_family
#print axioms Mobius.star5
#print axioms Mobius.mobius_family
