#!/usr/bin/env python3
"""gen_gpk.py k [k ...]: read search/gp<k>.json (output of gpsearch.py) and write the Lean modules
   ../src/GPn<k>T.lean (tables and definitions), ../src/GPn<k>W<i>.lean (window checks, split into chunks only to
   bound the memory of each compiler process) and ../src/GPn<k>.lean (the theorems).
   The module names, in build order, are appended to search/gp<k>.modules."""
import sys, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
BUDGET = int(os.environ.get('BUDGET', '300'))   # windows per chunk module
NL = chr(10)

def rows(lst, per=6):
    items = ['[' + ', '.join(map(str, r)) + ']' for r in lst]
    return '[' + (',' + NL + '    ').join(', '.join(items[i:i + per]) for i in range(0, len(items), per)) + ']'

def gen(k):
    d = json.load(open(os.path.join(HERE, 'gp%d.json' % k)))
    p, extra, q0, c0, N, n0 = d['p'], d['extra'], d['q0'], d['c0'], d['N'], d['n0']
    nmin = 2 * k + 1
    if d['bad']:   # small n without a star 5-edge-colouring (GP(3,1), the prism): start after them
        assert d['bad'] == list(range(nmin, nmin + len(d['bad']))), d['bad']
        nmin += len(d['bad'])
    pe = p * extra; W = 3 * k
    tabs = [d['P'] + d['S'][str(r)] for r in range(p)]
    small = [d['small'][str(n)] for n in range(nmin, n0)]
    ns = f'GPn{k}'
    # chunks [a, b) of n with about BUDGET windows each
    chunks = []; a = nmin; acc = 0
    for n in range(nmin, N):
        acc += n
        if acc >= BUDGET or n == N - 1:
            chunks.append((a, n + 1)); a = n + 1; acc = 0
    defs = f'''/-
  GPn{k}T.lean — generalized Petersen graphs GP(n,{k}), n ≥ {nmin}: the colouring (tables and definitions).

  GP(n,{k}) = `GPk.gp n {k}` (see GPPeriodic.lean): u_i = 2i, v_i = 2i+1; edges 3i: u_i u_{{i+1}}, 3i+1: u_i v_i,
  3i+2: v_i v_{{i+{k}}}.  Colouring: for n ≥ {n0} a periodic part of period {p} (patterns P0..P{p-1}; block
  J < n - n mod {p} - {pe} gets P_(J mod {p})) followed by a seam of length n mod {p} + {pe} that depends on n mod {p};
  explicit colourings for {nmin} ≤ n < {n0}.  A pattern is [outer, spoke, inner] with colours 0..4.
  The tables were found by a SAT search on 2026-10-02 (search/gpsearch.py, search/gp{k}.json); this file was generated
  by search/gen_gpk.py.  The Lean proof does not depend on the search: all windows are checked by `decide`.
-/
import GPPeriodic

namespace {ns}
open BlockStar GPk

/-- row r (r = n mod {p}): P0..P{p-1} followed by the seam for this residue -/
def tabs : List (List (List Nat)) :=
  [''' + (',' + NL + '   ').join(rows(t) for t in tabs) + f''']

/-- explicit colourings for n = {nmin}..{n0-1} (row n - {nmin}) -/
def smallTab : List (List (List Nat)) :=
  [''' + (',' + NL + '   ').join(rows(t) for t in small) + f''']

/-- index into row `n % {p}` of `tabs` of the pattern of block `J` -/
def idx (n J : Nat) : Nat :=
  if J < n - n % {p} - {pe} then J % {p} else {p} + (J - (n - n % {p} - {pe}))

/-- the pattern of block `J` -/
def chi (n J : Nat) : List Nat :=
  if n < {n0} then (smallTab.getD (n - {nmin}) []).getD J [] else (tabs.getD (n % {p}) []).getD (idx n J) []

/-- the colouring -/
def col (n : Nat) : Fin (gp n {k}).m → Fin 5 := bcol 3 ct ct_lt (chi n)

abbrev winsAll (n : Nat) : Prop :=
  ∀ j, j < n → winOK (gpkWir {k}) ct (fun _ => ()) (fun q => chi n ((j + q) % n)) = true

end {ns}
'''
    mods = [f'{ns}T']
    open(os.path.join(HERE, '..', 'src', f'{ns}T.lean'), 'w', encoding='utf-8', newline=NL).write(defs)
    for i, (a, b) in enumerate(chunks, 1):
        src = f'''/- GPn{k}W{i}.lean — window checks for GP(n,{k}), {a} ≤ n < {b} (generated by search/gen_gpk.py) -/
import {ns}T

namespace {ns}

theorem Wc{i} : ∀ n, n < {b} → {a} ≤ n → winsAll n := by decide +kernel

end {ns}
'''
        open(os.path.join(HERE, '..', 'src', f'{ns}W{i}.lean'), 'w', encoding='utf-8', newline=NL).write(src)
        mods.append(f'{ns}W{i}')
    imports = NL.join(f'import {ns}W{i}' for i in range(1, len(chunks) + 1))
    cases = []
    for i, (a, b) in enumerate(chunks, 1):
        if i < len(chunks):
            cases.append(f'  by_cases c{i} : n < {b}' + NL + f'  · exact Wc{i} n c{i} (by omega)')
        else:
            cases.append(f'  exact Wc{i} n h1 (by omega)')
    cases = NL.join(cases)
    main = f'''/-
  GPn{k}.lean — generalized Petersen graphs GP(n,{k}), n ≥ {nmin}: star edge colourings with 5 colours
  (colouring in GPn{k}T.lean, window checks for n < {N} in GPn{k}W1..{len(chunks)}.lean; generated by search/gen_gpk.py).
-/
{imports}

namespace {ns}
open BlockStar GPk

theorem Wsmall : ∀ n, n < {N} → {nmin} ≤ n → winsAll n := by
  intro n h1 h2
{cases}

theorem rep {{n : Nat}} (hn : {N} ≤ n) {{j : Nat}} (hj : j < n) :
    ∃ j', j' < {c0} + n % {p} ∧ ∀ q, q ≤ {W} →
      idx ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})) = idx n ((j + q) % n) := by
  have hm : ({c0} + n % {p}) % {p} = n % {p} := by omega
  rcases (show j + {W} < n - n % {p} - {pe} ∨ n - n % {p} - {pe} ≤ j + {W} by omega) with c | c
  · refine ⟨j % {p}, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega
  · refine ⟨j + ({c0} + n % {p}) - n, by omega, ?_⟩
    intro q hq
    rw [modc' hj (by omega), modc' (by omega) (by omega)]
    simp only [idx, hm]
    split_ifs <;> omega

/-- **GP(n,{k}).** For every `n ≥ {nmin}`, `col n` is a star edge colouring of GP(n,{k}) with 5 colours. -/
theorem star5 (n : Nat) (hn : {nmin} ≤ n) : (gp n {k}).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < {N}
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : {c0} + n % {p} < {N} := by omega
    refine ⟨fun _ => (), fun q => chi ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})), ?_,
      Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ {W} := hq
    refine ⟨rfl, ?_⟩
    have e := hrep q hq'
    have h1 : ¬ n < {n0} := by omega
    have h2 : ¬ {c0} + n % {p} < {n0} := by omega
    have hm : ({c0} + n % {p}) % {p} = n % {p} := by omega
    show chi ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e]

theorem subcubic (n : Nat) : (gp n {k}).Subcubic :=
  BG_subcubic _ _ _ (fun _ _ => ⟨fun _ => (), fun _ _ => rfl, by decide +kernel⟩)

/-- GP(n,{k}), n ≥ {nmin}: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem family (n : Nat) (hn : {nmin} ≤ n) : StarFam (gp n {k}) 5 :=
  ⟨subcubic n, gp_loopless n {k} (by decide) (by show max 1 {k} < n; omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end {ns}

#check @{ns}.star5
#check @{ns}.family
#print axioms {ns}.star5
#print axioms {ns}.family
'''
    open(os.path.join(HERE, '..', 'src', f'{ns}.lean'), 'w', encoding='utf-8', newline=NL).write(main)
    mods.append(ns)
    open(os.path.join(HERE, f'gp{k}.modules'), 'w').write(' '.join(mods) + NL)
    print('wrote', ' '.join(mods), '| p', p, 'extra', extra, 'N', N, 'n0', n0)

if __name__ == '__main__':
    for a in sys.argv[1:]: gen(int(a))
