#!/usr/bin/env python3
"""gen_ml.py: read search/ml.json (output of mlsearch.py) and write ../src/Mobius.lean."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); NL = chr(10)

def rows(lst, per=6):
    items = ['[' + ', '.join(map(str, r)) + ']' for r in lst]
    return '[' + (',' + NL + '    ').join(', '.join(items[i:i + per]) for i in range(0, len(items), per)) + ']'

d = json.load(open(os.path.join(HERE, 'ml.json')))
p, extra, q0, c0, N, n0 = d['p'], d['extra'], d['q0'], d['c0'], d['N'], d['n0']
assert extra >= 1 and d['bad'] == [3]
nmin = 4; pe = p * extra
tabs = [d['P'] + d['S'][str(r)] for r in range(p)]
small = [d['small'][str(n)] for n in range(nmin, n0)]
src = f'''/-
  Mobius.lean — Möbius ladders M_n (n rungs, 2n vertices), n ≥ 4: star edge colourings with 5 colours.
  (M_3 = K_{{3,3}} has star chromatic index 6.)

  M_n: cycle c_0 … c_{{2n-1}} with the chords c_i c_{{i+n}}.  Encoding as a cyclic block graph: block i = {{t_i, b_i}} with
  t_i = c_i = 2i, b_i = c_{{i+n}} = 2i+1 in `Fin (n * 2)`; edges of block i: 3i: t_i t_{{i+1}}, 3i+1: t_i b_i (the chord),
  3i+2: b_i b_{{i+1}} for i ≤ n−2, and for the last block (wiring kind 1): 3i: t_{{n-1}} b_0, 3i+2: b_{{n-1}} t_0.
  Colouring: for n ≥ {n0} a periodic part of period {p} followed by a seam of length n mod {p} + {pe}; explicit colourings
  for {nmin} ≤ n < {n0}; a pattern is [t-edge, chord, b-edge] with colours 0..4.  The tables were found by a SAT search on
  2026-10-02 (search/mlsearch.py, search/ml.json); generated by search/gen_ml.py.
-/
import Families
import GPPeriodic

namespace Mobius
open BlockStar SeamSeq GPk

def msrc (s : Nat) : Nat := match s with
  | 0 => 0 | 1 => 0 | _ => 1
def mjmp (s : Nat) : Nat := match s with
  | 1 => 0 | _ => 1
/-- head type of the edge type `s` in a block of wiring kind `w` (`w = 0`: normal, otherwise twisted) -/
def mdst (w s : Nat) : Nat := match s with
  | 0 => if w = 0 then 0 else 1
  | 1 => 1
  | _ => if w = 0 then 1 else 0

def mWir : Wir Nat 2 3 where
  D := 1
  src := fun _ s => msrc s
  jmp := fun _ s => mjmp s
  dst := mdst
  hsrc := by intro w s; unfold msrc; split <;> omega
  hdst := by intro w s; unfold mdst; split <;> first | omega | (split <;> omega)
  hjmp := by intro w s; unfold mjmp; split <;> omega
  jumps := [0, 1]
  hjmps := by intro w s; unfold mjmp; split <;> decide

/-- the Möbius ladder M_n: the last block `J = n - 1` is wired with the twist (`tw n J = 1`) -/
def mobius (n : Nat) : MGraph := BG mWir n (fun J => tw n J)

/-- row r (r = n mod {p}): P0..P{p-1} followed by the seam for this residue -/
def tabs : List (List (List Nat)) :=
  [''' + (',' + NL + '   ').join(rows(t) for t in tabs) + f''']

/-- explicit colourings for n = {nmin}..{n0-1} (row n - {nmin}) -/
def smallTab : List (List (List Nat)) :=
  [''' + (',' + NL + '   ').join(rows(t) for t in small) + f''']

def idx (n J : Nat) : Nat :=
  if J < n - n % {p} - {pe} then J % {p} else {p} + (J - (n - n % {p} - {pe}))

/-- the pattern of block `J` -/
def chi (n J : Nat) : List Nat :=
  if n < {n0} then (smallTab.getD (n - {nmin}) []).getD J [] else (tabs.getD (n % {p}) []).getD (idx n J) []

/-- the colouring -/
def col (n : Nat) : Fin (mobius n).m → Fin 5 := bcol 3 ct ct_lt (chi n)

abbrev winsAll (n : Nat) : Prop :=
  ∀ j, j < n → winOK mWir ct (fun q => tw n ((j + q) % n)) (fun q => chi n ((j + q) % n)) = true

theorem Wsmall : ∀ n, n < {N} → {nmin} ≤ n → winsAll n := by decide +kernel

theorem rep {{n : Nat}} (hn : {N} ≤ n) {{j : Nat}} (hj : j < n) :
    ∃ j', j' < {c0} + n % {p} ∧ ∀ q, q ≤ 3 →
      tw ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})) = tw n ((j + q) % n) ∧
      idx ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})) = idx n ((j + q) % n) := by
  have hm : ({c0} + n % {p}) % {p} = n % {p} := by omega
  rcases (show j + 3 < n - n % {p} - {pe} ∨ n - n % {p} - {pe} ≤ j + 3 by omega) with c | c
  · refine ⟨j % {p}, by omega, ?_⟩
    intro q hq
    rw [modc hj (by omega), modc (by omega) (by omega)]
    simp only [idx, tw, hm]
    constructor <;> split_ifs <;> omega
  · refine ⟨j + ({c0} + n % {p}) - n, by omega, ?_⟩
    intro q hq
    rw [modc hj (by omega), modc (by omega) (by omega)]
    simp only [idx, tw, hm]
    constructor <;> split_ifs <;> omega

/-- **Möbius ladders.** For every `n ≥ 4`, `col n` is a star edge colouring of M_n with 5 colours. -/
theorem star5 (n : Nat) (hn : {nmin} ≤ n) : (mobius n).Star 5 (col n) := by
  apply star_of_windows
  intro j hj
  by_cases c : n < {N}
  · exact ⟨_, _, fun q _ => ⟨rfl, rfl⟩, Wsmall n c hn j hj⟩
  · obtain ⟨j', hj', hrep⟩ := rep (by omega) hj
    have hn' : {c0} + n % {p} < {N} := by omega
    refine ⟨fun q => tw ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})),
      fun q => chi ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})), ?_, Wsmall _ hn' (by omega) j' hj'⟩
    intro q hq
    have hq' : q ≤ 3 := hq
    obtain ⟨e1, e2⟩ := hrep q hq'
    refine ⟨e1, ?_⟩
    have h1 : ¬ n < {n0} := by omega
    have h2 : ¬ {c0} + n % {p} < {n0} := by omega
    have hm : ({c0} + n % {p}) % {p} = n % {p} := by omega
    show chi ({c0} + n % {p}) ((j' + q) % ({c0} + n % {p})) = chi n ((j + q) % n)
    unfold chi
    rw [if_neg h1, if_neg h2, hm, e2]

theorem mobius_loopless (n : Nat) (hn : 2 ≤ n) : (mobius n).Loopless := by
  apply BG_loopless
  · show 1 < n
    omega
  · intro w s hs hz
    have hz' : mjmp s = 0 := hz
    show msrc s ≠ mdst w s
    have hs' : s < 3 := hs
    interval_cases s <;> first | exact absurd hz' (by decide) | simp [msrc, mdst]

theorem mobius_subcubic (n : Nat) (hn : 2 ≤ n) : (mobius n).Subcubic := by
  apply BG_subcubic
  intro j hj
  have two : ∀ q, q ≤ mWir.D → q = 0 ∨ q = 1 := by
    intro q hq
    have hq' : q ≤ 1 := hq
    omega
  rcases FlowerSnark.tw_cases hn hj with ⟨h0, h1⟩ | ⟨h0, h1⟩ | ⟨h0, h1⟩
  · refine ⟨fun q => [1, 0].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm
  · refine ⟨fun q => [0, 1].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm
  · refine ⟨fun q => [0, 0].getD q 0, ?_, by decide +kernel⟩
    intro q hq
    rcases two q hq with rfl | rfl
    · exact h0.symm
    · exact h1.symm

/-- Möbius ladders M_n, n ≥ 4: subcubic, loopless, every edge set star 5-colourable (and 6-colourable) -/
theorem mobius_family (n : Nat) (hn : {nmin} ≤ n) : StarFamily (mobius n) 5 :=
  ⟨mobius_subcubic n (by omega), mobius_loopless n (by omega),
    colourable_of_star (star5 n hn) (Nat.le_refl 5), colourable_of_star (star5 n hn) (by decide)⟩

end Mobius

#check @Mobius.star5
#check @Mobius.mobius_family
#print axioms Mobius.star5
#print axioms Mobius.mobius_family
'''
open(os.path.join(HERE, '..', 'src', 'Mobius.lean'), 'w', encoding='utf-8', newline=NL).write(src)
print('wrote Mobius.lean p', p, 'N', N, 'n0', n0)
